std/algebra/twistededwards/point.go
std/algebra/twistededwards/point_test.go

- Add `Neg` function for std/twistededwards/point
- Add tests for `Neg` function

Feature/Point: `Neg`

---

frontend/api.go
frontend/cs_api.go
internal/backend/circuits/lookup2.go
test/engine.go

Add lookup between four variables. Adds three constraints per lookup.

Add two-bit lookup

---

frontend/ccs.go
internal/backend/bls12-377/cs/r1cs.go
internal/backend/bls12-377/cs/r1cs_sparse.go
internal/backend/bls12-381/cs/r1cs.go
internal/backend/bls12-381/cs/r1cs_sparse.go
internal/backend/bls24-315/cs/r1cs.go
internal/backend/bls24-315/cs/r1cs_sparse.go
internal/backend/bn254/cs/r1cs.go
internal/backend/bn254/cs/r1cs_sparse.go
internal/backend/bw6-633/cs/r1cs.go
internal/backend/bw6-633/cs/r1cs_sparse.go
internal/backend/bw6-761/cs/r1cs.go
internal/backend/bw6-761/cs/r1cs_sparse.go
internal/backend/compiled/cs.go
internal/generator/backend/template/representations/r1cs.go.tmpl
internal/generator/backend/template/representations/r1cs.sparse.go.tmpl

Part of the gnark online playground; this returns a human readable representations of the constraint system.

feat: added ccs.GetConstraints

---

frontend/cs/plonk/api.go
std/algebra/twistededwards/bandersnatch/curve.go
std/algebra/twistededwards/bandersnatch/point.go
std/algebra/twistededwards/bandersnatch/point_test.go
std/algebra/twistededwards/curve.go
std/algebra/twistededwards/point.go
std/algebra/twistededwards/point_test.go
std/signature/eddsa/eddsa.go
std/signature/eddsa/eddsa_test.go

Reduce the number of constraints of a single EdDSA verification (e.g. Groth16/BN254 `-2049` constraints).

EdDSA gadget

---

go.mod
go.sum
internal/backend/bls12-377/plonk/prove.go
internal/backend/bls12-377/plonk/verify.go
internal/backend/bls12-381/plonk/prove.go
internal/backend/bls12-381/plonk/verify.go
internal/backend/bls24-315/plonk/prove.go
internal/backend/bls24-315/plonk/verify.go
internal/backend/bn254/plonk/prove.go
internal/backend/bn254/plonk/verify.go
internal/backend/bw6-633/plonk/prove.go
internal/backend/bw6-633/plonk/verify.go
internal/backend/bw6-761/plonk/prove.go
internal/backend/bw6-761/plonk/verify.go
internal/generator/backend/template/zkpschemes/plonk/plonk.prove.go.tmpl
internal/generator/backend/template/zkpschemes/plonk/plonk.verify.go.tmpl

Minor modifications on plonk according to the new kzg api (verifying an opening proof now requires the point at which the polynomial is opened).

feat: plonk adapted to kzg modifications

---

internal/backend/bls12-377/cs/r1cs.go
internal/backend/bls12-377/cs/r1cs_sparse.go
internal/backend/bls12-377/cs/solution.go
internal/backend/bls12-381/cs/r1cs.go
internal/backend/bls12-381/cs/r1cs_sparse.go
internal/backend/bls12-381/cs/solution.go
internal/backend/bls24-315/cs/r1cs.go
internal/backend/bls24-315/cs/r1cs_sparse.go
internal/backend/bls24-315/cs/solution.go
internal/backend/bn254/cs/r1cs.go
internal/backend/bn254/cs/r1cs_sparse.go
internal/backend/bn254/cs/solution.go
internal/backend/bw6-633/cs/r1cs.go
internal/backend/bw6-633/cs/r1cs_sparse.go
internal/backend/bw6-633/cs/solution.go
internal/backend/bw6-761/cs/r1cs.go
internal/backend/bw6-761/cs/r1cs_sparse.go
internal/backend/bw6-761/cs/solution.go
internal/backend/circuits/hint.go
internal/generator/backend/template/representations/r1cs.go.tmpl
internal/generator/backend/template/representations/r1cs.sparse.go.tmpl
internal/generator/backend/template/representations/solution.go.tmpl

- test: add failing test for #293
- fix: closes #293 and enables recursive hints solving

fix: closes #293 and enables recursive hints solving

---

std/algebra/fields_bls12377/e2.go
std/algebra/fields_bls24315/e2.go
std/algebra/fields_bls24315/e4.go
std/algebra/sw_bls12377/g1.go
std/algebra/sw_bls12377/g2.go
std/algebra/sw_bls12377/g2_test.go
std/algebra/sw_bls12377/inner.go
std/algebra/sw_bls24315/g1.go
std/algebra/sw_bls24315/g2.go
std/algebra/sw_bls24315/g2_test.go
std/algebra/sw_bls24315/inner.go
std/algebra/sw_bls24315/pairing.go

ported G1 scalarMul optimisations to G2 (needed for KZG verifier gadget).

[feat] G2 scalar multiplication

---

.github/workflows/pr.yml
.github/workflows/push.yml
backend/groth16/bellman_test.go
frontend/compiled/term.go
internal/utils/convert_test.go
std/algebra/fields_bls12377/e12_test.go
std/algebra/fields_bls12377/e2_test.go
std/algebra/fields_bls12377/e6_test.go
std/algebra/fields_bls24315/e12_test.go
std/algebra/fields_bls24315/e24.go
std/algebra/fields_bls24315/e24_test.go
std/algebra/fields_bls24315/e2_test.go
std/algebra/fields_bls24315/e4_test.go
std/algebra/sw_bls12377/g1_test.go
std/algebra/sw_bls12377/g2_test.go
std/algebra/sw_bls12377/pairing_test.go
std/algebra/sw_bls24315/g1_test.go
std/algebra/sw_bls24315/g2_test.go
std/algebra/sw_bls24315/pairing_test.go
std/fiat-shamir/transcript_test.go
std/groth16_bls12377/verifier_test.go
std/groth16_bls24315/verifier_test.go
std/hints_test.go

- build: update github action workflow with slack notif and golanglint ci
- build: fix golanglint ci warnings

ci: fix slack integration + adds golanglint-ci

---

internal/backend/bn254/groth16/solidity.go

Following #376 , some minor changes, see diff.
* more comments
* remove unused IC (vk.K) from the VerifyingKey structure
* remove "//last" iteration; initialize the input to accumulate function with vk.K[0] instead.
@citizen-stig : questions
1. Does it matter to inline the for loop? (ie use code generation for each iteration, rather than have them in the for loop to have a compact size if we have many inputs?)
2. Does it matter to use code generation to set the values of the vk.K (IC) verifying key directly before calling the scalar mul / point addition? (previously was refering the verifyingKey data structure in memory)

style: remove one add in groth16 solidity verifier, minor refactor

---

std/math/emulated/element_test.go
std/math/emulated/field.go
std/math/emulated/field_assert.go
std/math/emulated/field_ops.go
std/math/emulated/hints.go
std/math/emulated/wrapped_builder.go

fix: pack full limbs for quotient

---

std/hash/mimc/encrypt.go

This follows https://github.com/ConsenSys/gnark-crypto/pull/320

MiMC on BLS12-377 / number of rounds

---

doc.go

Update develop version to 0.8.1-alpha.

fix: update version

---

std/math/emulated/field_ops.go

Dunno how it got in but it causes confusion.

docs: fix select description in field emulation

---

std/signature/ecdsa/ecdsa_test.go

chore: remove heavy profiling and compiling

---

std/commitments/kzg_bls12377/verifier.go
std/commitments/kzg_bls24315/verifier.go

Same as https://github.com/ConsenSys/gnark-crypto/pull/386 but for SNARK circuits (2-chains).

Perf: KZG verification circuit in a single point

---

frontend/cs/commitment.go
test/commitments_test.go

This PR replaces the fake commitment placeholder with its idealization, true randomness.

fix: randomize fake commitments

---

backend/plonk/bn254/solidity.go

in `load_wire_commitments_commit_api`, replaced the loop counter by `vk_nb_commitments_commit_api` (instead of `2*vk_nb_commitments_commit_api` )
fixes #755

fix: loop counter corrected fixes #755

---

backend/plonk/bn254/solidity.go

G1 point in kzg SRS is generated by the template now...
fixes #768

fix: fixes #768

---

std/algebra/emulated/sw_emulated/point.go

Actually with more select logic and since we are using affine formulas, we can turn double-and-add to add-only while skipping some computations. This PR trades off the y-coordinate computation of the second addition for a select. This would correspond to Alg.1' [[Joye07]](https://www.iacr.org/archive/ches2007/47270135/47270135.pdf) + [[ELM03]](https://arxiv.org/abs/math/0208038).
*new bench*
```
ecrecover (r1cs):  303521
ecrecover (scs):  1455938
ecmul (r1cs):  183756
ecmul (scs):  876507
```
*old bench*
```
ecrecover (r1sc):  365237
ecrecover (scs):  1767044
ecmul (r1sc):  244988
ecmul (scs):  1183191
```

perf: ELM03+Joye07 for emulated scalarMul

---

std/algebra/emulated/sw_emulated/point.go

At each iteration we have 4 `Select` and a `doubleAndAdd` which is either `2R0+R1` or `2R1+R0`. This PR implements a conditional `doubleAndAdd` that first always computes the x-coordinate of `R0+R1` and then adds either `R0` or `R1` based on a `Select`. This saves 1 `Select` at each iteration. 
The PR also substitutes `AddUnified` with simple `add` in the last `bit=0` iteration in `JointScalarMulBase`, which is only used in ECRECOVER where the `scalar=0` edge case does not occur.
The total savings in PLONK for precompiles are:
*ECRECOVER: -11427 scs*
*ECMUL: -2016 scs*

Perf: save 1 `Select` at each iteration in the emulated `scalarMul`

---

go.mod
go.sum

chore: update gnark-crypto dependency

---

backend/plonk/bn254/solidity.go

Same as #791 but based on `develop`.

perf: cache array index - 200 gas

---

doc.go

Update version tag to fix CI tests.

test: update version tag

---

go.mod
go.sum

Upgrading the github.com/consensys/compress dependency (Using 37-bit long backrefs)
Fixes # (issue)
All existing tests pass.
No benchmarking

Upgrade `compress` dependency to v0.2.5

---

std/compress/lzss/snark.go
std/compress/lzss/snark_test.go

Currently the decompressor guarantees to pad its output with zeros. Providing an option for not doing that can save one constraint per output byte.
`TestNoZeroPaddingOutput`
No benchmark

perf allow for dirty padding of decompression output

---

backend/plonk/bls12-377/prove.go
backend/plonk/bls12-381/prove.go
backend/plonk/bls24-315/prove.go
backend/plonk/bls24-317/prove.go
backend/plonk/bn254/prove.go
backend/plonk/bn254/solidity.go
backend/plonk/bw6-633/prove.go
backend/plonk/bw6-761/prove.go
doc.go
internal/generator/backend/template/zkpschemes/plonk/plonk.prove.go.tmpl

style: remove old todos

---

backend/groth16/bn254/solidity.go
frontend/cs/scs/builder.go
frontend/schema/walk.go
profile/profile_worker.go
std/commitments/kzg/verifier.go
std/math/emulated/composition.go
std/recursion/plonk/verifier.go
std/signature/ecdsa/ecdsa.go

Update TODOs and add comments to some existing TODOs.
Currently there are still a few of TODOs open for `std/math/uints` package, but it is still work in progress and didn't update those.

docs: update TODOs

---

go.mod
go.sum
internal/generator/backend/main.go
internal/tinyfield/element.go
internal/tinyfield/element_test.go
internal/tinyfield/vector.go
internal/tinyfield/vector_test.go

Update to latest gnark-crypto, fix compile error for tinyfield generation.

feat: update to latest gnark-crypto

---

std/math/polynomial/polynomial.go
test/assert.go

fix some function names in comment
Fixes # (issue)

chore: fix some function names in comment

---

std/evmprecompiles/hints.go

chore: fix error message 

---

std/algebra/emulated/sw_bls12381/pairing.go

Fix for https://github.com/Consensys/gnark/pull/1349#discussion_r1884605103. Silences linters.

chore: remove duplicate nil-check

---

std/math/emulated/emparams/emparams.go
std/math/emulated/field_assert.go
std/permutation/poseidon2/poseidon2.go

fix: spellchecker 

---

std/hash/ripemd160/ripemd160_test.go
std/math/bitslice/partition.go
version_test.go

chore: fix typos

---

frontend/api.go
std/commitments/fri/fri.go
std/hash/mimc/mimc_test.go

fix some struct names in comment

chore: fix some struct names in comment

---

constraint/solver/hint_registry.go

This is a [new function](https://pkg.go.dev/maps@go1.21.1#Clone) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use maps.Clone to simplify the code and reorder packages

---

std/algebra/emulated/sw_bn254/pairing.go

remove redundant word in comment

chore: remove redundant word in comment

---

frontend/schema/tags.go

Using the Cut method added to the standard library in 1.18, the code can be more concise.

refactor: use strings.Cut
