Consensys/gnark

README.md

just a missing "to" (I think this is the correct fix. feel free to change of course)
library looks great!

add missing word in readme

---

Makefile

makefile-gopath: use go env GOPATH instead of the OS's GOPATH environment variable

---

frontend/cs.go

Implements a two line methods `(*ConstraintSystem).NbConstraints()` that would enable constraints profiling and let the user know how many constraints have been created between two points of the circuit definition.

features(profiling): Adds a way to print the number of constraints in the circuit

---

go.mod
go.sum
internal/backend/bls377/groth16/verify.go
internal/backend/bls381/groth16/verify.go
internal/backend/bn256/groth16/verify.go
internal/backend/bw761/groth16/verify.go
internal/generators/backend/template/zkpschemes/groth16.verify.go.tmpl

`Pair([a,c,e],[b,d,f])` is slower than `FE( ML(a,b) * ML(c,d) * ML(e,f)` when used with goroutines (concurrent to `mulExp`).
instead of using `Pair([a,c,e],[b,d,f])` , this PR uses `tmp = ML([a,c],[b,d])` in a goroutine and then `FE( tmp * ML(e,f) )` after the `mulExp` is done.

MillerLoops and goroutine

---

frontend/circuit.go
frontend/cs_api.go
go.sum
integration_test.go
internal/backend/bls377/groth16/groth16_test.go
internal/backend/bls377/r1cs_test.go
internal/backend/bls381/groth16/groth16_test.go
internal/backend/bls381/r1cs_test.go
internal/backend/bn256/groth16/groth16_test.go
internal/backend/bn256/r1cs_test.go
internal/backend/bw761/groth16/groth16_test.go
internal/backend/bw761/r1cs_test.go
internal/backend/circuits/and.go
internal/backend/circuits/assertequal.go
internal/backend/circuits/circuits.go
internal/backend/circuits/div.go
internal/backend/circuits/exp.go
internal/backend/circuits/frombinary.go
internal/backend/circuits/inv.go
internal/backend/circuits/iszero.go
internal/backend/circuits/or.go
internal/backend/circuits/range.go
internal/backend/circuits/reference_small.go
internal/backend/circuits/xor00.go
internal/backend/circuits/xor01.go
internal/backend/circuits/xor10.go
internal/backend/circuits/xor11.go
internal/generators/backend/template/representations/tests/r1cs.go.tmpl
internal/generators/backend/template/zkpschemes/tests/groth16.go.tmpl

Fixes #45 
Addition of Or, And, IsZero constraints.
**Example**:
Referring to the use in #45 here is an example:
` type ExampleCircuit struct {
X frontend.Variable
}
func (circuit *ExampleCircuit) Define(curveID gurvy.ID, cs *frontend.ConstraintSystem) error {
XminusThree := cs.Sub(circuit.X, 3)
XminusFour := cs.Sub(circuit.X, 4)
isXEqualToThree := cs.IsZero(XminusThree, curveID)
isXEqualToFour := cs.IsZero(XminusFour, curveID)
xEqualThreeOrFour := cs.Or(isXEqualToThree, isXEqualToFour)
cs.Println("x==3?: ", isXEqualToThree)
cs.Println("x==4?: ", isXEqualToFour)
cs.Println("x==3 or x==4?: ", xEqualThreeOrFour)
cs.AssertIsEqual(xEqualThreeOrFour, 1)
return nil
}
func main() {
var circuit ExampleCircuit
r1cs, _ := frontend.Compile(gurvy.BN256, &circuit)
var solution ExampleCircuit …

Addition of Or,And constraint, plus a specific constraint checking if a value is zero

---

frontend/cs.go
frontend/cs_api.go
frontend/variable.go
internal/backend/bls377/cs/r1cs.go
internal/backend/bls381/cs/r1cs.go
internal/backend/bn256/cs/r1cs.go
internal/backend/bw761/cs/r1cs.go
internal/backend/compiled/r1c.go
internal/generators/backend/template/representations/r1cs.go.tmpl

Inverse and Div were adding constraints without cloning the underlying linear expressions, resulting in multiple offsetting of the variable IDs when building a R1CS.

fix: inverse and div in frontend had some variable ID offset issues

---

std/signature/eddsa/eddsa.go
std/signature/eddsa/eddsa_test.go

In EdDSA, the `S` scalar in the signature is now split in 2, to prevent overflowing --> S should NOT be reduced modulo r, the size of the snark field. So if n is the bit length of r, S is split in S1, S2 such that S = 2^(n/2)S1+S2, so S1 and S2 are the digits of S in basis 2^(n/2).
The signature struct is now
```
type Signature struct {
R      twistededwards.Point
S1, S2 frontend.Variable // --> instead of: S frontend.Variable
}
```
Examples of how to properly split S given a signature is in std/signature/eddsa/eddsa_test.go. If r is n-bits long, splitting S amounts to take the first n/2 bits of the part of the signature corresponding to S for S1, and the last n/2 bits of the part of the signature corresponding to S for S2 (the signature is a byte slice point||S, the first n-bits chunk is …

docs: added comments for the splitting of S in eddsa

---

frontend/cs.go
frontend/cs_test.go
internal/backend/bls12-377/cs/r1cs_test.go
internal/backend/bls12-381/cs/r1cs_test.go
internal/backend/bn254/cs/r1cs_test.go
internal/backend/bw6-761/cs/r1cs_test.go
internal/backend/circuits/determinism.go
internal/backend/compiled/r1c.go
internal/generator/backend/template/representations/tests/r1cs.go.tmpl

This PR makes the compilation to r1cs deterministic. 
Non determinism came from the `reduce` function in frontend/cs.go. The function has been made deterministic by sorting the variables ID in the reduced linear expression.
A specific test circuit has been added to trig non determinism when the the variables are not sorted in `reduce`.

PR to fix the non determinism of r1cs compilation

---

backend/groth16/groth16.go
frontend/cs.go
frontend/cs_api.go
internal/backend/bls12-377/groth16/prove.go
internal/backend/bls12-377/groth16/setup.go
internal/backend/bls12-381/groth16/prove.go
internal/backend/bls12-381/groth16/setup.go
internal/backend/bls24-315/groth16/prove.go
internal/backend/bls24-315/groth16/setup.go
internal/backend/bn254/groth16/prove.go
internal/backend/bn254/groth16/setup.go
internal/backend/bw6-761/groth16/prove.go
internal/backend/bw6-761/groth16/setup.go
internal/generator/backend/template/zkpschemes/groth16/groth16.prove.go.tmpl
internal/generator/backend/template/zkpschemes/groth16/groth16.setup.go.tmpl

fixes:
* `groth16.Prove` with `force=true` wasn't doing much since msm with zeroes don't do much. 
perf:
* `groth16.Setup` produces `pk.G1.A`, `pk.G1.B` and `pk.G2.B`, derived from the QAP. However, if a variable doesn't appear in a QAP column, the value of the corresponding interpolation vector is 0, and the resulting point in the proving key is infinity. 
Additionally, `frontend.newR1C` will put the variable with the longest linear expression in the `A` part of the QAP, maximizing the number of zeroes in the `B` part. 
In one internal circuit, using a lot of `MiMC`, this speeds up `groth16.Prove` by ~30%.

groth16: filter points at infinity in setup

---

frontend/cs_api.go
frontend/cs_to_r1cs_sparse.go
internal/backend/bls12-377/cs/r1cs.go
internal/backend/bls12-377/cs/r1cs_sparse.go
internal/backend/bls12-381/cs/r1cs.go
internal/backend/bls12-381/cs/r1cs_sparse.go
internal/backend/bls24-315/cs/r1cs.go
internal/backend/bls24-315/cs/r1cs_sparse.go
internal/backend/bn254/cs/r1cs.go
internal/backend/bn254/cs/r1cs_sparse.go
internal/backend/bw6-761/cs/r1cs.go
internal/backend/bw6-761/cs/r1cs_sparse.go
internal/backend/circuits/iszero.go
internal/backend/compiled/r1c.go
internal/generator/backend/template/representations/r1cs.go.tmpl
internal/generator/backend/template/representations/r1cs.sparse.go.tmpl

Fixes #132 . 
Note that the way the solver was extended is likely to be superseded by #133 .

perf: `cs.IsZero` uses 3 constraints

---

backend/groth16/groth16.go
internal/backend/bls12-377/groth16/groth16_test.go
internal/backend/bls12-377/groth16/marshal.go
internal/backend/bls12-381/groth16/groth16_test.go
internal/backend/bls12-381/groth16/marshal.go
internal/backend/bls24-315/groth16/groth16_test.go
internal/backend/bls24-315/groth16/marshal.go
internal/backend/bn254/groth16/groth16_test.go
internal/backend/bn254/groth16/marshal.go
internal/backend/bw6-761/groth16/groth16_test.go
internal/backend/bw6-761/groth16/marshal.go
internal/generator/backend/template/zkpschemes/groth16/groth16.marshal.go.tmpl
internal/generator/backend/template/zkpschemes/groth16/tests/groth16.go.tmpl
internal/generator/backend/template/zkpschemes/groth16/tests/groth16.marshal.go.tmpl
io/io.go

Can now decode `groth16.ProvingKey` and `groth16.VerifyingKey` without doing subgroup checks on the points. 
Usage:
```
pk.UnsafeReadFrom(reader)
```
In some cases, subgroup check can be done at the application level once, and `gnark` user can ensure through other means (checksum, signatures, ...) that the `ProvingKey` /  `VerifyingKey` are legit.

feat: added UnsafeReadFrom for groth16 Proving and Verifying keys

---

std/algebra/fields/e12.go
std/algebra/fields/e12_test.go
std/algebra/fields/e2.go
std/algebra/fields/e6.go
std/algebra/sw/g2.go
std/algebra/sw/pairing.go
std/algebra/sw/pairing_test.go

This PR reduces the number of constraints (R1CS) of a pairing to ~~12674~~ 12339

[std] Pairing circuit

---

.github/workflows/develop.yml
debug_test.go
examples/rollup/circuit_test.go
frontend/cs.go
frontend/cs_api.go
frontend/cs_api_test.go
frontend/cs_to_r1cs.go
frontend/cs_to_r1cs_sparse.go
frontend/frontend.go
frontend/frontend_test.go
frontend/fuzz.go
internal/backend/compiled/r1c.go
std/algebra/fields/e12_test.go
std/algebra/sw/g1_test.go
test/assert.go
test/options.go

* fixes #155  slow plonk compile
* fixes #163 detects unconstrained inputs
API change:
* adds `frontend.CompileOptions` which enables to set initial capacity (as previously) and to ignore compiler error if unconstrained inputs are detected
Internal:
* when splitting linear expression in plonk frontend, do less gcd and less linear expression division.

fixes #155 slow plonk compile, fixes #163 detects unconstrained inputs

---

std/algebra/twistededwards/bandersnatch/curve.go
std/algebra/twistededwards/bandersnatch/point.go
std/algebra/twistededwards/bandersnatch/point_test.go

A proposition to add bandersnatch curve (in twisted Edwards form) to gnark. This PR implements Bandersnatch as a separate package from `twistededwards` mainly because each companion curve is identified by the base curve ID (e.g. BLS12-381 for both Bandersnatch and Jubjub). This has the advantage to keep backward compatibility but duplicates the exact same code. The other option is to create in gnark-crypto an ID for companion curves but gnark users should update their code.

Add Bandersnatch curve

---

debug/debug.go
debug/debug_full.go
frontend/cs_api.go
frontend/cs_assertions.go
frontend/cs_debug.go
frontend/frontend.go
frontend/variable.go
internal/backend/compiled/log.go
test/engine.go

Example, when testing / building with no tags (default):
```
Error:          groth16(bn254): [assertIsEqual] 35 == 62
cubic.(*Circuit).Define
cubic.go:35
witness:{
"Public": {
"Y": "35"
},
"Secret": {
"x": "3"
}
}
Test:           TestCubicEquation
```
With `-tags=debug`
```
Error:          groth16(bn254): [assertIsEqual] 35 == 62
test.IsSolved.func1
/Users/gbotrel/dev/go/src/github.com/consensys/gnark/test/engine.go:80
runtime.gopanic
/usr/local/go/src/runtime/panic.go:1038
test.(*engine).AssertIsEqual
/Users/gbotrel/dev/go/src/github.com/consensys/gnark/test/engine.go:263
cubic.(*Circuit).Define
/Users/gbotrel/dev/go/src/github.com/consensys/gnark/examples/cubic/cubic.go:35
witness:{
"Public": {
"Y": "35"
},
"Secret": {
"x": "3"
}
}
Test:           TestCubicEquation
```

feat: lighter stack trace by default for circuits, more verbose when -tags=debug provided

---

backend/backend.go
backend/hint/builtin.go
backend/hint/hint.go
backend/hint/registry.go
frontend/api.go
frontend/cs.go
internal/backend/bls12-377/cs/solution.go
internal/backend/bls12-381/cs/solution.go
internal/backend/bls24-315/cs/solution.go
internal/backend/bn254/cs/solution.go
internal/backend/bw6-761/cs/solution.go
internal/generator/backend/template/representations/solution.go.tmpl

Added hint registry for registering hint functions used in gadgets. Improved the documentation to help explain the usage of hints.
Todo:

Add hint registry

---

frontend/cs.go

The internal method which computes the constants in the constraint system didn't reduce the integers by the modulus.
Closes #203. Needs to be ported on top of #200.

Reduce constant values by the modulus

---

circuitstats_test.go
integration_test.go
internal/backend/bls12-377/cs/r1cs_test.go
internal/backend/bls12-381/cs/r1cs_test.go
internal/backend/bls24-315/cs/r1cs_test.go
internal/backend/bn254/cs/r1cs_test.go
internal/backend/bw6-633/cs/r1cs_test.go
internal/backend/bw6-761/cs/r1cs_test.go
internal/backend/circuits/lookup2.go
internal/generator/backend/template/representations/tests/r1cs.go.tmpl
test/assert.go

Added method `Run(fn func(assert *test.Assert), descs ...string)` to Assert type. This is similar to the `Run` method in Go's standard testing package to allow running subtests. Refactored tests in places to use subtests.
Removed explicit `Fuzz` call in integration tests as Fuzz is already called in `Assert.ProverSucceeded`.
An potential added benefit of using subtests is better coverage with race detector and enabling running subtests in parallel. I didn't implement it now though as Assert uses unsynchronized cache for compiled circuits.

Add subtests to test.Assert

---

backend/groth16/groth16.go
backend/plonk/plonk.go
frontend/ccs.go
frontend/compile.go
frontend/cs/plonk/conversion.go
frontend/cs/r1cs/conversion.go
internal/backend/bls12-377/groth16/groth16_test.go
internal/backend/bls12-377/plonk/plonk_test.go
internal/backend/bls12-381/groth16/groth16_test.go
internal/backend/bls12-381/plonk/plonk_test.go
internal/backend/bls24-315/groth16/groth16_test.go
internal/backend/bls24-315/plonk/plonk_test.go
internal/backend/bn254/groth16/groth16_test.go
internal/backend/bn254/plonk/plonk_test.go
internal/backend/bw6-633/groth16/groth16_test.go
internal/backend/bw6-633/plonk/plonk_test.go
internal/backend/bw6-761/groth16/groth16_test.go
internal/backend/bw6-761/plonk/plonk_test.go
internal/generator/backend/template/zkpschemes/groth16/tests/groth16.go.tmpl
internal/generator/backend/template/zkpschemes/plonk/tests/plonk.go.tmpl
std/algebra/fields_bls24315/e24_test.go
std/algebra/sw_bls12377/g1_test.go
std/algebra/sw_bls24315/g1_test.go
std/algebra/twistededwards/bandersnatch/point_test.go
std/fiat-shamir/transcript_test.go
std/groth16_bls12377/verifier_test.go
std/groth16_bls24315/verifier_test.go
test/assert.go
test/kzg_srs.go

Introduced by #200  --> 
`frontend.CompiledConstraintSystem` became `compiled.ConstraintSystem`, but `compiled` is `internal/` . 
Note that `GetCounters() []compiled.Counter` in the interface returns something from `internal` which may be impractical  / need revisit.

Re-exposed frontend.CompiledConstraintSystem

---

backend/hint/builtin.go
backend/hint/hint.go
backend/hint/registry.go
frontend/api.go
frontend/cs/plonk/api.go
frontend/cs/plonk/conversion.go
frontend/cs/plonk/sparse_r1cs.go
frontend/cs/r1cs/api.go
frontend/cs/r1cs/conversion.go
frontend/cs/r1cs/r1cs.go
internal/backend/bls12-377/cs/solution.go
internal/backend/bls12-381/cs/solution.go
internal/backend/bls24-315/cs/solution.go
internal/backend/bn254/cs/solution.go
internal/backend/bw6-633/cs/solution.go
internal/backend/bw6-761/cs/solution.go
internal/backend/circuits/hint.go
internal/backend/compiled/cs.go
internal/generator/backend/template/representations/solution.go.tmpl
test/engine.go
test/engine_test.go

This is an API breaking PR - the `frontend.API` interface changes to allow multiple outputs and now also returns errors (in case the inputs do not correspond to the hint signature).
This is still a draft PR - some tests fail with PLONK backend, but waiting for the refactoring and then will try again.
It is based on top of #191. As it is not yet merged, then this PR also contains commits from that PR but will be rebased later.

Add multiple outputs for a hint function

---

frontend/api.go
frontend/cs/plonk/api.go
frontend/cs/r1cs/api.go
integration_test.go
internal/backend/circuits/cmp.go
test/engine.go

This PR adds the Cmp function to the api:
```
// Cmp returns 1 if i1>i2, 0 if i1=i2, -1 if i1<i2
Cmp(i1, i2 Variable) Variable
```
following [this](https://github.com/ConsenSys/gnark/discussions/199) discussion.
~4k constraints for BN254.

feat: addition of Cmp in the API

---

debug_test.go
frontend/ccs.go
internal/backend/bls12-377/cs/r1cs.go
internal/backend/bls12-377/cs/r1cs_sparse.go
internal/backend/bls12-377/cs/solution.go
internal/backend/bls12-381/cs/r1cs.go
internal/backend/bls12-381/cs/r1cs_sparse.go
internal/backend/bls12-381/cs/solution.go
internal/backend/bls24-315/cs/r1cs.go
internal/backend/bls24-315/cs/r1cs_sparse.go
internal/backend/bls24-315/cs/solution.go
internal/backend/bn254/cs/r1cs.go
internal/backend/bn254/cs/r1cs_sparse.go
internal/backend/bn254/cs/solution.go
internal/backend/bw6-633/cs/r1cs.go
internal/backend/bw6-633/cs/r1cs_sparse.go
internal/backend/bw6-633/cs/solution.go
internal/backend/bw6-761/cs/r1cs.go
internal/backend/bw6-761/cs/r1cs_sparse.go
internal/backend/bw6-761/cs/solution.go
internal/backend/circuits/cmp.go
internal/generator/backend/template/representations/r1cs.go.tmpl
internal/generator/backend/template/representations/r1cs.sparse.go.tmpl
internal/generator/backend/template/representations/solution.go.tmpl

This PR removes the `ccs.ToHTML` deadcode. It's not `gnark` job to produce HTML, the constraint system returns a list of formatted constraints in a `[][]string` and a user (like play.gnark.io ) can then render it. 
`ccs.GetConstraints` returns for PlonK the constraints in the form `qL⋅xa + qR⋅xb + qO⋅xc + qM⋅(xaxb) + qC == 0` (as in the paper) and for Groth16 `L⋅R == O` . 
Additionally, this PR adds a constraint ID number in the message for a unsatisfied constraint at solving time.

`ccs.GetConstraints` readable output

---

internal/backend/compiled/cs.go

fix: use uint64 for cbor unmarshal and cast

---

internal/backend/bls12-377/cs/r1cs.go
internal/backend/bls12-377/cs/r1cs_sparse.go
internal/backend/bls12-377/cs/solution.go
internal/backend/bls12-381/cs/r1cs.go
internal/backend/bls12-381/cs/r1cs_sparse.go
internal/backend/bls12-381/cs/solution.go
internal/backend/bls24-315/cs/r1cs.go
internal/backend/bls24-315/cs/r1cs_sparse.go
internal/backend/bls24-315/cs/solution.go
internal/backend/bn254/cs/r1cs.go
internal/backend/bn254/cs/r1cs_sparse.go
internal/backend/bn254/cs/solution.go
internal/backend/bw6-633/cs/r1cs.go
internal/backend/bw6-633/cs/r1cs_sparse.go
internal/backend/bw6-633/cs/solution.go
internal/backend/bw6-761/cs/r1cs.go
internal/backend/bw6-761/cs/r1cs_sparse.go
internal/backend/bw6-761/cs/solution.go
internal/generator/backend/template/representations/r1cs.go.tmpl
internal/generator/backend/template/representations/r1cs.sparse.go.tmpl
internal/generator/backend/template/representations/solution.go.tmpl

--> solveWithHint was doing useless mod reduce on the big int inputs (already mod reduce when computing linear expression with fr.Element)
--> solveWithHint was leaking a big.Int from the pool; anyway, seems for hint heavy workflows, better to just allocate a big.Int slice 👍

perf: replace big int pool in hint solver by tmp slice

---

std/algebra/sw_bls12377/g1.go
std/algebra/sw_bls24315/g1.go

When the scalar is constant (big.Int), there is no need to use `Lookup2` conditional. Instead we can just `Acc.DoubleAndAdd(Acc, table[k[0].Bit(i)+2*k[1].Bit(i)])`. This doesn't change the R1CS count (same mul complexity) but reduces the sparse_R1CS (PlonK) count by almost **2k** constraints.

constScalarMul for SW gadget

---

std/algebra/twistededwards/bandersnatch/point.go
std/algebra/twistededwards/point.go

rearranging addition to cost 1C less.

addition on twisted Edwards

---

backend/hint/builtin.go
backend/hint/hint.go
frontend/api.go
frontend/cs/plonk/api.go
frontend/cs/r1cs/api.go
internal/backend/bls12-377/cs/solution.go
internal/backend/bls12-381/cs/solution.go
internal/backend/bls24-315/cs/solution.go
internal/backend/bn254/cs/solution.go
internal/backend/bw6-633/cs/solution.go
internal/backend/bw6-761/cs/solution.go
internal/backend/circuits/hint.go
internal/generator/backend/template/representations/solution.go.tmpl
std/algebra/sw_bls12377/g1.go
std/algebra/sw_bls24315/g1.go
test/engine.go
test/engine_test.go

Creating this one as draft before cleaning it as it opens a discussion. It reverts some changes introduced by #183  #175  (cc @ivokub ). 
Essentially, this PR proposes to remove `nbInputs` and `nbOutputs` set in `StaticHintFunction` and the `NbOutputs()` function in the `Hint` interface. 
Trying to implement multi-outputs (with variable length) hints for binary operation, this declarative way is really not helping;
1. The circuit developer will provide a list of inputs to the hint function (example; `api.NewHint(myHint, input0, input1, ...)`. IF (and I don't think we need to) we want to check that the number of inputs matches what the hints can process, it's up to the hint to perform the check (ie if len(inputs) > ... --> error). Currently this was encapsulated in a `Call` function. 
2. …

Simplify hints declaration and make frontend responsible for number of outputs, not hint / backend

---

backend/hint/builtin.go
examples/exponentiate/exponentiate.go
frontend/api.go
frontend/cs/r1cs/api.go
frontend/cs/r1cs/api_assertions.go
frontend/cs/scs/api.go
frontend/cs/scs/api_assertions.go
std/hints.go
std/math/bits/conversion.go
std/math/bits/conversion_binary.go
std/math/bits/conversion_ternary.go
std/math/bits/conversion_test.go
std/math/bits/naf.go
std/math/bits/naf_test.go
test/assert.go
test/engine_test.go

Closes #269 . 
This PR adds `std/math/bits` with `ToBase` `FromBase` (`ToBinary` `ToTernary`) and `ToNAF` circuit functions. 
`ToTernary` and `ToNAF` generates some unnecessary constraints but will be fixed with #243 . 
This PR keeps `api.ToBinary` (which calls `bits.ToBinary` ) since other part of `api` depends on binary decomposition (range checks).

Adds std/math/bits

---

frontend/compile.go
frontend/cs/r1cs/builder.go
frontend/cs/scs/builder.go

🙈 --> we used to do a weird dance in a post-compile phase, where we would loop through all constraints, logs, debuginfo, hints, and offset the ids of the wires. This was unnecessary complicated; new version just count the number of public and secret variables before calling `Define`, so, the r1cs builder and plonk builder both know the offset to add to new internal wires... voila. 
- feat: remove post-compile offset id in R1CS builder
- feat: remove offset shifts in plonk compile

simplify post compile phase: shifting wire id is not needed 🙈 

---

frontend/compile.go
test/assert.go
test/kzg_srs.go

additionally, adds a bit of parallelism in the Assert object, after the compile phase.
Not extremely efficient since most algorithms after the compile phase are already parallel.

Fixes #283 : ensure test.Assert compile cache handles different objects of same type

---

internal/stats/snippet.go
std/algebra/fields_bls12377/e12.go
std/algebra/fields_bls12377/e12_test.go
std/algebra/fields_bls12377/e2.go
std/algebra/fields_bls12377/e2_test.go
std/algebra/fields_bls12377/e6.go
std/algebra/fields_bls12377/e6_test.go
std/algebra/fields_bls24315/e12.go
std/algebra/fields_bls24315/e12_test.go
std/algebra/fields_bls24315/e2.go
std/algebra/fields_bls24315/e24.go
std/algebra/fields_bls24315/e24_test.go
std/algebra/fields_bls24315/e2_test.go
std/algebra/fields_bls24315/e4.go
std/algebra/fields_bls24315/e4_test.go
std/algebra/sw_bls12377/g2.go
std/algebra/sw_bls12377/g2_test.go
std/algebra/sw_bls12377/pairing.go
std/algebra/sw_bls12377/pairing_test.go
std/algebra/sw_bls24315/g2.go
std/algebra/sw_bls24315/g2_test.go
std/algebra/sw_bls24315/pairing.go
std/algebra/sw_bls24315/pairing_test.go
std/groth16_bls12377/verifier.go
std/groth16_bls12377/verifier_test.go
std/groth16_bls24315/verifier.go
std/groth16_bls24315/verifier_test.go

- fix: remove unused pairingContext.BTwistCoeff
- fix: remove unused pairingContext.BTwistCoeff
- clean: remove PairingContext and Extension objects from api calls in std/../pairing

clean: remove PairingContext and Extension objects from api calls in std/.../pairing

---

test/engine.go

Adds blank whitespace between the variables in test engine's `Println` method.

fix: add whitespace between vars in test.Println

---

internal/backend/bls12-377/cs/solution.go
internal/backend/bls12-381/cs/solution.go
internal/backend/bls24-315/cs/solution.go
internal/backend/bn254/cs/solution.go
internal/backend/bw6-633/cs/solution.go
internal/backend/bw6-761/cs/solution.go
internal/generator/backend/template/representations/solution.go.tmpl

Let the solver return the errors of the recursively solved hints instead of panicking. Otherwise fuzzer fails if hint returns an error on invalid input.

fix: err instead of panic when recursively solving hints

---

std/groth16_bls12377/verifier.go
std/groth16_bls12377/verifier_test.go
std/groth16_bls24315/verifier.go
std/groth16_bls24315/verifier_test.go

- clean: std/groth16 notation matches out-of-circuit Groth16 notation
- clean: std/groth16 notation matches out-of-circuit Groth16 notation

clean: std/groth16 uses same notation as out-of-circuit groth16

---

test/assert.go
test/engine.go
test/engine_test.go

Added options for the test engine and moved a an argument into the option. Additionally, added a new option for wrapping API and a boolean for defining the return value of the methods `ConstantValue` and `IsConstant`.
API wrapping was done to ease the testing of existing circuits using non-native field arithmetic.
Option for defining the constant values can be used to verify different code-paths in the circuits. I also changed the way fuzzer works -- now it checks that the test engine solves the circuit for both option and only if the test engine succeeds for both options (all vars constants or not), calls the actual prover.

feat: implement test engine options

---

std/math/nonnative/composition.go
std/math/nonnative/doc.go
std/math/nonnative/hints.go
std/math/nonnative/variable.go
std/math/nonnative/variable_test.go

Slight fixes needed for lazy reduction and limb grouping for faster equality check.
Is blocked by #302 and will rebase after it is merged.
Related #315.

perf[nonnative]: implement optimisations for field emulation

---

std/math/nonnative/variable.go

To check that the product of two non-native elements is correct, we consider the elements as polynomials and check that the corresponding polynomial evaluations are equal. I was doing one less evaluation as started indexing from 1, not 0.

fix(nonnative): off by one error

---

frontend/builder.go
frontend/compile.go
frontend/cs/r1cs/api.go
frontend/cs/r1cs/builder.go
frontend/cs/scs/api.go
frontend/cs/scs/builder.go
frontend/schema/field.go
frontend/schema/schema.go
frontend/schema/tags_test.go
internal/backend/bls12-377/witness/witness.go
internal/backend/bls12-381/witness/witness.go
internal/backend/bls24-315/witness/witness.go
internal/backend/bn254/witness/witness.go
internal/backend/bw6-633/witness/witness.go
internal/backend/bw6-761/witness/witness.go
internal/generator/backend/template/representations/witness.go.tmpl
internal/tinyfield/witness/witness.go
test/engine.go
test/fuzz.go
test/solver_test.go

In the upcoming fake-API for field emulation branch I have implemented a wrapper for `frontend.Builder` which initialises the variables in the circuit witness. The builder also needs to modify the parsed schema (for example, we need a native element for every limb). For that, the `LeafHandler` now takes as input `*schema.Field` which it can modify in-place.
I think this PR may not be optimal. Will try to rebase fake-API branch on top of this one to see how it would be used in practice.

refactor: allow builder to interact with schema parser

---

internal/backend/circuits/div.go
test/engine.go

At every API call utils.FromInterface method was called. This method always
allocates new *big.Int, which is very stressful for the runtime. Instead, we
first check if the variable is already *big.Int and return it otherwise. Only
if type assertion fails do we allocate new *big.Int.
Now, as we do not allocate every time, we had to change the API calls to
allocate a new result, so that we wouldn't mutate the passed in values.

perf: allocate less in test engine

---

frontend/compile.go
std/math/nonnative/api.go
std/math/nonnative/api_test.go
std/math/nonnative/hints.go
std/math/nonnative/variable.go
std/math/nonnative/variable_test.go

feat: implement API using non-native field emulation

---

internal/backend/bls12-377/cs/r1cs.go
internal/backend/bls12-381/cs/r1cs.go
internal/backend/bls24-315/cs/r1cs.go
internal/backend/bn254/cs/r1cs.go
internal/backend/bw6-633/cs/r1cs.go
internal/backend/bw6-761/cs/r1cs.go
internal/generator/backend/template/representations/r1cs.go.tmpl

fix misspelled word  `decsribes` to `describes` in the comment of struct `R1CS`

fix: misspelled ("decsribes" ->  "describes")

---

CONTRIBUTING.md

Fix: minor typo

---

CONTRIBUTING.md
internal/backend/bls12-377/cs/r1cs.go
internal/backend/bls12-381/cs/r1cs.go
internal/backend/bls24-315/cs/r1cs.go
internal/backend/bn254/cs/r1cs.go
internal/backend/bn254/groth16/solidity.go
internal/backend/bw6-633/cs/r1cs.go
internal/backend/bw6-761/cs/r1cs.go
internal/generator/backend/template/representations/r1cs.go.tmpl

Existing implementation of Pairing library allocated additional memory on each addition and multiplication, which can quadratically increase gas cost with larger public input.
This PR addresses several things:
1. Allocates single array for each operation and reuses them between
2. Changes declaration of `input` from `memory` to `calldata`. Ideally public input should be constructed off-chain and remain only in call data. It is important to notice, that caller smart contract might already do it, but EVM implicitly copy call data to memory, which is not needed in this case.

Optimize bn254/groth16 solidity verifier.

---

internal/backend/bls12-377/plonkfri/prove.go
internal/backend/bls12-377/plonkfri/verify.go
internal/backend/bls12-381/plonkfri/prove.go
internal/backend/bls12-381/plonkfri/verify.go
internal/backend/bls24-315/plonkfri/prove.go
internal/backend/bls24-315/plonkfri/verify.go
internal/backend/bls24-317/plonkfri/prove.go
internal/backend/bls24-317/plonkfri/verify.go
internal/backend/bn254/plonkfri/prove.go
internal/backend/bn254/plonkfri/verify.go
internal/backend/bw6-633/plonkfri/prove.go
internal/backend/bw6-633/plonkfri/verify.go
internal/backend/bw6-761/plonkfri/prove.go
internal/backend/bw6-761/plonkfri/verify.go
internal/generator/backend/template/zkpschemes/plonkfri/plonk.prove.go.tmpl
internal/generator/backend/template/zkpschemes/plonkfri/plonk.verify.go.tmpl
test/assert.go

During the completion of the public witness in the verification phase, we compute a linear combination whose coefficients are the Lagrange polynomials, evaluated at a challenge point. With FRI, the set of challenges contains the vanishing domain of the polynomial relations. If the challenge belongs to this domain, then the recursive formulas to compute the Lagrange polynomials fails because there is a division by zero.
This exceptional case is handled now.
Fixes #349

fix: fixed Lagrange polynomials construction

---

frontend/circuit.go
frontend/compile.go
frontend/schema/schema.go
frontend/schema/schema_test.go
frontend/schema/tags.go
std/math/emulated/element.go
std/math/emulated/element_test.go

Resolves #385.
This PR adds new "inherit" tag to the circuit which allows inherit the visibility of the parent object. Useful for custom defined types.
Meanwhile, updated also some comments to take advantage of new go doc formatting rules (links and lists).

feat: add inherit circuit tag

---

frontend/compile.go
frontend/cs/r1cs/api.go
frontend/cs/r1cs/builder.go
frontend/cs/r1cs/r1cs_test.go

Closes #417.
With the refactored frontend and constraint system, the memory usage has gone down a lot and the operations are a lot more efficient with fr.Elements. This option isn't necessary for keccak-f and emulated ECDSA anymore, and helps slightly for  BN254 pairing, but I didn't try too much different parameters.

feat: compress linear expression

---

test/engine.go

Currently such a test fails:
```go
type testPrintCircuit struct {
Var frontend.Variable
}
func (c *testPrintCircuit) Define(api frontend.API) error {
api.Println("testing", c.Var)
api.AssertIsEqual(c.Var, 0)
return nil
}
func TestPrintSolve(t *testing.T) {
circuit := testPrintCircuit{}
assignment := testPrintCircuit{0}
NewAssert(t).SolvingSucceeded(
&circuit, &assignment, WithBackends(backend.GROTH16), WithCurves(ecc.BN254))
}
```
It is useful to have descriptive strings in print statements. This PR enables that.

fix: engine.Println to take strings

---

std/math/emulated/field_ops.go

Previously the result of MulConst had non-zero overflow when multipling a constant by a small constant. This panics Reduce method which assumes that constants have zero overflow.
Fixes #431
The PR doesn't include the initial test because circuit called `EnforceWidth()` on the public witness and as fuzzer provides random inputs (where the width of the witness may be longer than assumed), then leads false failure. See also #296.

fix: add shortcut for const input in MulConst

---

constraint/bls12-377/r1cs_test.go
constraint/bls12-381/r1cs_test.go
constraint/bls24-315/r1cs_test.go
constraint/bls24-317/r1cs_test.go
constraint/bn254/r1cs_test.go
constraint/bw6-633/r1cs_test.go
constraint/bw6-761/r1cs_test.go
constraint/level_builder.go
constraint/system.go
constraint/tinyfield/r1cs_test.go
internal/generator/backend/template/representations/tests/r1cs.go.tmpl

When building dependency graph of constraints, we can encounter in a single constraint many wires which are the output of a hint h1. 
This hint h1 can have itself many inputs; this PR just marks hints as already "visited" to avoid an exponential blowup.

fix: handle recursive hints in level builder

---

test/assert.go
test/options.go

The new testing option allows to run assertions on `test.Assert` without fuzzing. My use case for running tests without fuzzing is in gadget where some errors panic to simplify the API.
Additionally, I was not sure if we should omit fuzzing when the tests are run in short mode? Should we?

feat: add NoFuzzing() testing option

---

std/math/emulated/field_ops.go
test/engine.go

We previously modified the result inline, but the behaviour may be inconsistent with actual frontend/compiler. When variable is a Term or LinearExpression, then
```
b := a
```
copies value of a into b and after that these variables are independent. For example, with MulAcc(b, x, y) we won't modify the variable a. But, as test engine modified variable inline, then doing MulAcc(b, x, y) also changed value of a (as they are just *big.Int). This lead to inconsistent results.

fix: allocate new variable in engine.MulAcc

---

frontend/cs/r1cs/builder.go
frontend/cs/scs/builder.go
internal/kvstore/kvstore.go
test/engine.go
test/solver_test.go

With new gadgets, we may have some state we want to store over different calls. Instead of using singletons (essentially global variables), we instead add a `map[any]any` to the builders which allow to store builder-local variables.
To prevent overuse of the map, we dont publish the methods publicly in the `frontend.API`, but instead embed an instance in the builders themselves. If a gadget wants to use the storage, then they first have to type-assert the frontend.API instance to `kvstore.Store` and then on the new variable call `SetKeyValue` and `GetKeyValue`.
Another great aspect of having `any` keys is that we can use any comparable types (comparable because map implementation requires so). This allows us to avoid any collisions by enforcing that the keys are of different type. See the …

feat: add simple key-value store to the builders

---

frontend/builder.go
frontend/cs/r1cs/builder.go
frontend/cs/scs/builder.go
go.mod
internal/backend/bls12-377/groth16/commitment_test.go
internal/backend/bls12-381/groth16/commitment_test.go
internal/backend/bls24-315/groth16/commitment_test.go
internal/backend/bls24-317/groth16/commitment_test.go
internal/backend/bn254/groth16/commitment_test.go
internal/backend/bw6-633/groth16/commitment_test.go
internal/backend/bw6-761/groth16/commitment_test.go
internal/generator/backend/template/zkpschemes/groth16/tests/groth16.commitment.go.tmpl
test/engine.go

Right now `Commit` is part of the `frontend.Compiler` API. But this doesn't work well in case where the builders actually do not implement commitment (e.g. PLONK). We will get a runtime panic but this is really difficult to detect in a way which is sustainable long term (string handling etc.).
So instead, I add a new interface `Committer` with a single method `Commit` (as previously in `frontend.Compiler`). If the builder implements commitments, then any user can type assert and use the method and otherwise rely on some locally-defined fallback.
I also added a simple and hopefully fast enough commitment to the test engine. And removed the commitment from PLONK for now until we implement augmented-PLONK

refactor: define Committer interface for builders

---

debug/debug.go
debug/symbol_table.go
frontend/builder.go
frontend/compile.go
frontend/cs/r1cs/builder.go
frontend/cs/r1cs/r1cs_test.go
frontend/cs/scs/builder.go
internal/circuitdefer/defer.go
test/engine.go
test/engine_test.go
test/solver_test.go

See discussion in #472. This PR adds `PreCompileHook(cb func(API) error)` method to the `frontend.Compiler`. The intent of the method is to register all callback which should be called after the `Define` method of the circuit is called. These callbacks can be used by gadgets to safely defer any necessary closing tasks (e.g. range checking builds actual constraints, permutation networks build the permutations etc.) without requiring any interaction from the user.
I don't like the implementation though, I think it is really fragile. However, the problem is that I do not want to make `frontend.Compile` interface any more complex than it barely should, and this also means that there isn't a method to get all the callbacks which the `frontend.Compile` method can use. That is why I have …

feat: add defer to the Compiler interface

---

std/math/emulated/field.go

fix: restrict constants in field emulation to width

---

backend/witness/witness_test.go
debug/debug.go
debug/symbol_table.go
frontend/compile.go
test/engine.go
test/solver_test.go

This PR improves the stacks with deferred functions. We previously stopped stack collection when encountered method `Define`. I tried adding another break for if we encounter the method `callDeferred`. However, when running in non-debug mode, then there was a override for functions in files in `frontend/` directory. This override overrode the `callDeferred` breakpoint. I further specified it to `frontend/cs` so that the function `callDeferred` in `frontend/compile.go` wouldn't be skipped.
Added `callDeferred` to test engine to have consistent behaviour.
This seems to fix the failing tests in #472 (non-determinism).

fix: handle stack traces with deferred function

---

frontend/api.go
std/math/emulated/field_ops.go

Now we are using MulAcc, which assigns to the input argument. As the limbs are used elsewhere, then we actually modify the input arguments to `Field.Mul` and get inconsistencies.

fix: initialize new variable if field emulation multiplication check

---

constraint/level_builder.go
constraint/level_builder_test.go

Fixes cause from #529.
`System.lbHints` wasn't stable over different compiles and our deterministic compilation check failed. Now clean the internal cache where we use pointers.

fix: stable levelbuilder hint mapping

---

frontend/cs/r1cs/api.go

Related #504.
In order to enable running full test suite where we use commitments we need to have the commitment available for the solver. I don't know what is a good way to do this, but this patch allows to continue with #472.
First, I register the hint in `frontend/r1cs` init. This gives solver access to the hint when run in the same process as the compiler. The hint is private so it isn't possible to provide it manually.
We also check if either debug tag is set or we run as a Go test (i.e. the executable name ends in `.test`). Only so we have a dummy commitment (zero).
Otherwise, we return an error, as before.

fix: allow unreplaced BSB22 commitment hint in solver

---

std/math/emulated/field_assert.go
test/assert.go

Fixes the bugs found by the fuzzer. I also added logging to the fuzzer when it finds the inputs which create inconsistent result. Otherwise it is quite time-consuming to recreate the bug.

fix: do not pass limb width enforcement for consts in AssertIsEqual

---

std/math/bits/conversion.go
std/math/bits/conversion_test.go

When `nbDigits` is set to a number that is less than the length of the binary representation of the input, a proof can not be generated. That's because the `api.AssertIsEqual(Σbi, v)` constraint can not be satisfied. The description of `WithNbDigits` needs to be fixed.

docs: correct `WithNbDigits` description

---

frontend/cs/r1cs/api.go

For safety, we use mocked commitment hint only when running in tests or in debug mode. This is to avoid using it by accident in real application, as the mocked commitment is not sound.
The test if we are in testing environment didn't consider Windows and this made CI tests fail.
EDIT: another approach is to not have the check at all, but I think it gives a bit more of safety.

fix: use mocked api.Commit also in Windows tests

---

std/math/emulated/field_hint.go
std/math/emulated/field_hint_test.go
test/options.go

We used to have hints when we hade fake-API. @yelhousni recommends reintroducing as it is helpful for optimising non-native algebra (pairings etc). When I tried to reintroduce the implementation then I realized that actually the old code (already removed few months ago) was kind of broken. We wrapped the hint functions and created anonymous hint functions, which cannot really work.
So, I rewrote it, making defining hints slightly more inconvenient. So instead of writing:
```go
func HintFn(mod *big.Int, inputs []*big.Int, outputs []*big.Int) error {
// work here
}
```
we do
```go
func HintFn(mod *big.Int, inputs, outputs []*big.Int) error {
return emulated.UnwrapHint(inputs, outputs,
func(mod *big.Int, inputs, outputs []*big.Int) error { // NB we shadow initial input, output, mod to avoid …
```

feat: reintroduce hints for field emulation

---

std/evmprecompiles/01-ecrecover.go
std/evmprecompiles/01-ecrecover_test.go
std/evmprecompiles/02-sha256.go
std/evmprecompiles/04-id.go
std/evmprecompiles/05-expmod.go
std/evmprecompiles/06-bnadd.go
std/evmprecompiles/07-bnmul.go
std/evmprecompiles/08-bnpairing.go
std/evmprecompiles/bn_test.go
std/evmprecompiles/compose.go
std/evmprecompiles/doc.go
std/evmprecompiles/hints.go
std/hints.go
std/math/emulated/field.go

Closes #466.
Even if we have many primitives, then this PR is introducing tightly coupled circuits for using with EVM precompiles. The goal is that we can take verbatim precompile call arguments and return whatever implementations would return.
Still WIP, but starting a draft PR for discussions on interfaces etc. Need to fix #484 as with test engine right now get errors where shouldn't.
More specifically:
Tasks:

feat: add EVM precompiles

---

std/selector/multiplexer.go
std/selector/multiplexer_test.go

A 2 to 1 multiplexer is a special case and has an efficient solution which can not be generalized to other cases:
```
out == sel * i_1 + (1 - sel) * i_0
sel * (sel - 1) == 0
```
Therefore, we should use `api.Select` for constructing 2 to 1 multiplexers as a special case.

perf: use `api.Select` for 2 to 1 mux

---

constraint/commitment.go

See the issue here: #645 
Change the original code:
```go
func (i *Commitment) SerializeCommitment(privateCommitment []byte, publicCommitted []*big.Int, fieldByteLen int) []byte {
res := make([]byte, len(privateCommitment)+len(publicCommitted)*fieldByteLen)
copy(res, privateCommitment)
offset := len(privateCommitment)
for j, inJ := range publicCommitted {
offset += j * fieldByteLen
inJ.FillBytes(res[offset : offset+fieldByteLen])
}
return res
}
```
to
```go
func (i *Commitment) SerializeCommitment(privateCommitment []byte, publicCommitted []*big.Int, fieldByteLen int) []byte {
res := make([]byte, len(privateCommitment)+len(publicCommitted)*fieldByteLen)
copy(res, privateCommitment)
offset := len(privateCommitment)
for _, inJ := range publicCommitted {
inJ.FillBytes(res[offset : …
```

[BUG FIX] constraint: serializeCommitment

---

constraint/bls12-377/coeff.go
constraint/bls12-377/r1cs_test.go
constraint/bls12-381/coeff.go
constraint/bls12-381/r1cs_test.go
constraint/bls24-315/coeff.go
constraint/bls24-315/r1cs_test.go
constraint/bls24-317/coeff.go
constraint/bls24-317/r1cs_test.go
constraint/blueprint_hint.go
constraint/blueprint_r1cs.go
constraint/blueprint_scs.go
constraint/bn254/coeff.go
constraint/bn254/r1cs_test.go
constraint/bw6-633/coeff.go
constraint/bw6-633/r1cs_test.go
constraint/bw6-761/coeff.go
constraint/bw6-761/r1cs_test.go
constraint/core.go
constraint/hint.go
constraint/level_builder.go
constraint/r1cs_test.go
constraint/system.go
constraint/tinyfield/coeff.go
constraint/tinyfield/r1cs_test.go
frontend/cs/r1cs/builder.go
frontend/cs/scs/api.go
frontend/cs/scs/api_assertions.go
frontend/cs/scs/builder.go
internal/generator/backend/template/representations/coeff.go.tmpl
internal/generator/backend/template/representations/tests/r1cs.go.tmpl

Example for a 1000 MiMC:
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkCompileMiMC-10     226517208     170724021     -24.63%
benchmark                   old allocs     new allocs     delta
BenchmarkCompileMiMC-10     4101305        2656976        -35.22%
benchmark                   old bytes     new bytes     delta
BenchmarkCompileMiMC-10     363802628     181183808     -50.20%
```

perf: reduce mem allocs in scs frontend

---

std/algebra/emulated/sw_emulated/point.go
std/evmprecompiles/01-ecrecover.go
std/signature/ecdsa/ecdsa.go

In ECDSA verification (or ECRecover), we compute `[r/s]pubKey + [h/s]g` where `(r,s)` is the signature, `h` the hash of the message and `g` the canonical generator of the subgroup. Previously, we took into consideration the edge cases where either or both `r` and `h` can be 0 and also `pubKey=(0,0)`, but the [EYP](https://ethereum.github.io/yellowpaper/paper.pdf) rules out these:
- `s ≠ 0` and `r ≠ 0`
- `pubKey ≠ (0,0)` (because private key `≠ 0`)
The PR introduces the `JointScalarMulBase` method which performs `[s1]p1 + [s2]g` assuming that `s1` and `s2` are nonzero and `p1` not the infinity `(0,0)`. This saves ~17k constraints in ECDSA verifier gadget.

perf(ecdsa): JoinScalarMulBase avoids 0 edge-cases

---

backend/witness/witness_test.go
frontend/schema/schema.go
frontend/schema/schema_test.go
frontend/schema/walk.go

Types in the circuit definition can implement `frontend.GnarkInitHook` interface. When a type implements this interface, then it knows how to initialise itself. This is useful for example in field emulation where we use it to allocate the limbs, allowing to correctly estimate the size of the native elements in the witness.
However, we currently didn't call the init hook when initable types were elements of arrays and slices. This PR implements calling init hooks both in `schema.Parse` and `schema.Walk`.
Fixes #680 and also a lot of "ignoring uninitialized slice" errors.

fix: init elements in arrays and slices if have init hook

---

std/evmprecompiles/01-ecrecover.go
std/evmprecompiles/01-ecrecover_test.go

Ethereum Yellow paper defines two initial conditions for ECRecover:
* in case of checking transaction signatures, `s` should be `s < N+2 + 1`
* in case of ECREC precompile, `s` should be `s < N`.
This PR updates the current precompile method which takes additional variable which defines the upper bound to compare s against. Also added test cases (strict check, lax check, assumed failure).
This is based on top of `fix/ecdsa-v` which depends on update in gnark-crypto. So have to wait for other PRs being merged before can merge this one.
CC: @AlexandreBelling, @OlivierBBB -- can you confirm this behaviour is good?

feat: differentiate ecrecover with strict and lax check for s

---

std/math/emulated/emparams/emparams.go
std/math/emulated/emulationparams/emulationparams.go
std/math/emulated/params.go

I was implementing ECDSA verification over P-384 and meanwhile saw a few things to improve:
* for Goldilocks field use the modulus from gnark-crypto instead of hardcoding. Makes easier to review when there is only a single definition.
* same for secp256k1 base and scalar fields. Previously weren't available in gnark-crypto but now is, so makes more sense to refer.
* moved emulation parameters into new package to decrease the number of implemented types and methods there. This hopefully makes it easier for the users to find the methods they are actually interested in. I enforce type aliases for existing parameters not to break any existing code.
* structured the type descriptions for types which implement FieldParams. Now everything is bullet pointed and modulus is in separate code-block …

refactor: emulation parameters

---

std/algebra/native/sw_bls12377/g1.go
std/algebra/native/sw_bls12377/g2.go

While looking into a question about emulated ScalarMul, I noticed we can further merge some `Double`+ `Add` into a `DoubleAndAdd` to reduce the number of constraints. Hence the tiny PR.
- Old
```
BenchmarkVarScalarMulG1
g1_test.go:460: groth16 1548
BenchmarkVarScalarMulG1/plonk
g1_test.go:471: plonk 3861
BenchmarkVarScalarMulG2
g2_test.go:496: groth16 4250
BenchmarkVarScalarMulG2/plonk
g2_test.go:507: plonk 12604
```
- New:
```
BenchmarkVarScalarMulG1
g1_test.go:460: groth16 1544
BenchmarkVarScalarMulG1/plonk
g1_test.go:471: plonk 3858
BenchmarkVarScalarMulG2
g2_test.go:496: groth16 4240
BenchmarkVarScalarMulG2/plonk
g2_test.go:507: plonk 12579
```

perf(2-chain/varScalarMul): use DoubleAndAdd to reduce #constraints

---

backend/groth16/bls12-377/setup.go
backend/groth16/bls12-381/setup.go
backend/groth16/bls24-315/setup.go
backend/groth16/bls24-317/setup.go
backend/groth16/bn254/setup.go
backend/groth16/bw6-633/setup.go
backend/groth16/bw6-761/setup.go
internal/generator/backend/template/zkpschemes/groth16/groth16.setup.go.tmpl
test/commitments_test.go

More compact tests for commitments (one test method iterating over prepared circuits) similar to elsewhere in the repo

refactor: compactify commitment tests

---

std/math/emulated/element_test.go
std/math/emulated/field_binary.go

We modreduced when the input was constant, but did not when it was a variable. For ECDSA we assert against the modulus which was constant and modreduced.
Need to apply to plonk branch.

fix: emulated ToBits

---

backend/plonk/bn254/solidity.go

Added missing proof length check, fixes #735

feat: [PLONK_AUDIT_4-11] fixes #735

---

constraint/bls12-377/system.go
constraint/bls12-381/system.go
constraint/bls24-315/system.go
constraint/bls24-317/system.go
constraint/blueprint_logderivlookup.go
constraint/bn254/system.go
constraint/bw6-633/system.go
constraint/bw6-761/system.go
constraint/tinyfield/system.go
internal/generator/backend/template/representations/system.go.tmpl
std/lookup/logderivlookup/logderivlookup.go

1. 
```
panic: error reading scs : cbor: exceeded max number of elements 134217728 for CBOR array
```
--> seems now we can do `2147483647` as max size, easy fix, lucky for us :) 
2. 
```
panic: cbor: cannot unmarshal map into Go struct field cs.system.Blueprints of type constraint.Blueprint
```
--> suspect this comes from `BlueprintLookupHint` 
We need to figure out a better way to serialize blueprints, this fix should do for now, but we need to re-serialize the circuits (cc @AlexandreBelling )

fix: plonk scs serialization issues

---

backend/plonk/bls12-377/marshal.go
backend/plonk/bls12-377/setup.go
backend/plonk/bls12-381/marshal.go
backend/plonk/bls12-381/setup.go
backend/plonk/bls24-315/marshal.go
backend/plonk/bls24-315/setup.go
backend/plonk/bls24-317/marshal.go
backend/plonk/bls24-317/setup.go
backend/plonk/bn254/marshal.go
backend/plonk/bn254/setup.go
backend/plonk/bw6-633/marshal.go
backend/plonk/bw6-633/setup.go
backend/plonk/bw6-761/marshal.go
backend/plonk/bw6-761/setup.go
go.mod
go.sum
internal/generator/backend/template/zkpschemes/plonk/plonk.marshal.go.tmpl
internal/generator/backend/template/zkpschemes/plonk/plonk.setup.go.tmpl
internal/tinyfield/vector.go
internal/tinyfield/vector_test.go

This PR uses new gnark-crypto `AsyncReadFrom` methods inside `plonk.ProvingKey` `ReadFrom` method.
This allows to consumes bytes from the reader (most likely `os.File`), not block the rest of the file reading while doing some pre-compute operations.
This PR also parallelize the `computeLagrangeCosetPolys` doing bunch of FFTs . Surprinsingly, this alone improves wall clock of large PK deserialization by 50%. 
Total improvement PR 2- 3x.

perf: async parallel plonk pr read

---

std/algebra/emulated/sw_emulated/point.go
std/algebra/emulated/sw_emulated/point_test.go
std/evmprecompiles/07-bnmul.go

I was trying to have a `ScalarMul()` circuit with only additions and no doublings. Ultimately, I could make the circuit work with less constraints than the previous right-to-left double-and-add circuit. So I looked in the literature to check if it was previously known and I found that Marc Joye *of course* did it in 2007 😅
So this PR corresponds actually to Alg.2 of [[CHES:Joye07]](https://www.iacr.org/archive/ches2007/47270135/47270135.pdf) with some tweaks to make it work efficiently in-circuit: 
- select-logic with an additional register;
- isolate first iteration and use [[ELM02]](https://eprint.iacr.org/2002/112) `triple()` method;
- isolate last iteration and discard `R1` and `R2` computations.
Now when we use this new method in precompiles it saves:
- `ECRECOVER`: 
- 17 609 r1cs
- …

Perf: Add-only emulated scalar multiplication

---

std/algebra/emulated/sw_bn254/pairing.go
std/algebra/emulated/sw_bn254/pairing_test.go

One more optim while writing the blog post: In the case of multi-pairings, when `bit=0` we can first store the lines in the first loop and then iterate on them in the second loop while multiplying them together 2-by-2 before multiplying by the accumulator.
```go
l1 := make([]*lineEvaluation, n)
// ...
switch loopCounter[i] {
case 0:
// precompute lines
for k := 0; k < n; k++ {
// Qacc[k] ← 2Qacc[k] and l1 the tangent ℓ passing 2Qacc[k]
Qacc[k], l1[k] = pr.doubleStep(Qacc[k])
// line evaluation at P[k]
l1[k].R0 = *pr.MulByElement(&l1[k].R0, xOverY[k])
l1[k].R1 = *pr.MulByElement(&l1[k].R1, yInv[k])
}
// if number of lines is odd, mul last line by res
// works for n=1 as well
if n%2 != 0 {
// ℓ × res
res = pr.MulBy034(res, &l1[n-1].R0, &l1[n-1].R1)
}
// mul lines 2-by-2
for k := 1; k < n; k …
```

Perf: emulated pairing BN254

---

backend/plonk/bn254/solidity.go

the openings (= values) of the proof commitments are ensured to be below r_mod : fixes #743

feat: [PLONK_AUDIT_4-8] fixes #743

---

backend/plonk/bn254/solidity.go

added pairing check result: fixes #741

feat: [PLONK_AUDIT_4-4] fixes #741

---

backend/plonk/bn254/solidity.go

I added checks on each of the staticcalls instructions following this doc: 
- https://blog.soliditylang.org/2021/04/21/custom-errors/.
The contract now reverts if for instance not enough gas is supplied in the static calls.
The other solution was to update the `state_success` in the memory but it was messy, and there was no error message...
fixes #753

feat: status of staticcalls are checked, fixes #753

---

backend/plonk/bn254/solidity.go

The value `z**n-1` is needed several times in the code and was recomputed. Now it is computed once in `compute_pi`. The function returns `z**n-1` in addition to the public inputs contribution. `z**n-1` is then stored in the memory dedicated to the state.
Fixes #774

feat: zeta_power_n_minus_one save and reused in compute_pi

---

backend/plonk/bn254/solidity.go

The logic is to generate a bytes32 and concat it with a bytes16 to create the 48 elements. 
That can then be converted piece by piece to uint8 in the hash_fr instead
20000 gas savings with this.

streamline msg expansion

---

std/polynomial/polynomial.go
std/polynomial/polynomial_test.go

Evaluation of large multilinear extensions is a major bottleneck in GKR verification. Currently the hypercube bases are evaluated at the requested point and the linear combination of these results with the corresponding hypercube values is taken. A massive reduction in the number of constraints can be achieved by performing successive foldings instead. For the 20-variable case we get
```
develop:
r1cs: 2100657 constraints
scs : 4194301 constraints
opt1 (successive fold):
r1cs: 1048576 constraints 49%
scs: 3145726 constraints 75%
```
a 25% improvement for SCS.
A second optimization defers scaling of folding operations which is corrected at the end. My experiments suggest that this starts paying off at around the $2^{16}$ size. It doesn't help with R1CS at all, but doesn't hurt …

Perf: Improve MultiLin.Eval number of constraints

---

backend/plonk/bn254/solidity.go

* removed Utils library
* hash_fr is written in assembly
@julien-marchand there might be some conflicts with the 'calldataisation' :/

feat: hash_fr in assembly + removed Utils

---

backend/plonk/bn254/solidity.go

In order to not waste gas in gas of a failure, the math functions (ec_add, ec_mul, etc) revert immediately in case of failure.
Until now we updated the variable stored at `add(mload(0x40), add(mload(0x40), state_success)` and continued the execution until the end even in case of failure.
Now at `state_success` we store only the result of the actual checks related to the proof, which are
* the verification of the constraints at a random point
* the KZG openings

feat: staticcall fails -> revert immediately instead of updating state_success

---

std/algebra/emulated/sw_bls12381/pairing.go
std/algebra/emulated/sw_bn254/pairing.go
std/algebra/native/sw_bls12377/pairing.go
std/algebra/native/sw_bls12377/pairing_test.go
std/algebra/native/sw_bls24315/pairing.go
std/algebra/native/sw_bls24315/pairing_test.go

@feltroidprime pointed out this morning that pre-computing `-x/y` in emulated pairings would save lines negations at each double/add step in the Miller loop. While it shouldn't in native fields, the idea is interesting for emulated fields. I tried this for 2-chains and emulated BN254 and BLS12-381:
- For 2-chains it does not save anything for both Groth16 and Plonk, as expected.
- For emulated pairings however, the results are a bit weird because of how field emulation works (@ivokub any explanation?): 
- For BLS12-381, it does not save anything in Groth16.
- For BN254, we lose -385 constraints in Groth16.
However this PR is worth it for Plonk because the addition gates are not free. We save 5960 constraints for BLS12-381 and 2896 for BN254. I applied the changes to 2-chains as well, to …

Perf: save some negations in emulated pairings

---

backend/plonk/bn254/solidity.go
backend/plonk/bn254/verify.go
internal/generator/backend/template/zkpschemes/plonk/plonk.verify.go.tmpl

Fiat Shamir changes in plonk are added in the solidity template

fs in solidity compliant with the go implem

---

frontend/cs/scs/api.go
frontend/cs/scs/api_test.go

Currently a `MulAcc` in Plonk always outputs two constraints. This PR saves one constraint for the special case of `a(b+1) = a + ab`.
- Performance improvement
- `TestMulAccFastTrack` in `frontend/cs/scs/api_test.go`
- The same test ensures that no more than one constraint is created.

perf: a special case for mulacc

---

std/algebra/emulated/fields_bls12381/e12_pairing.go
std/algebra/emulated/fields_bn254/e12_pairing.go
std/algebra/emulated/sw_bls12381/pairing.go
std/algebra/emulated/sw_bn254/pairing.go

With the upcoming pr #749 it is necessary that we do not change the limb values of `emulated.Element` values. Mostly the API is designed in a way that this doesn't happen (we pass in and out pointers and do not perform in-place modifications), but there are a few cases in nonnative algebra where the API is overridden. This is mostly due to that for structs containing nonnative elements we need to use the value instead of pointer to count the number of field elements to allocate and have initialized values.
For example, if we have definition like:
```go
type G1Affine struct {
X, Y emulated.Element[emparams.BN254Fp]
}
```
and we compute
```go
var P G1Affine
P = curve.Add(c.G, c.Q)
P.X = *emulated.Add(&p.X, other)
```
then we modify the value `P.X`. Now, as the multiplication checks are …

chore: avoid nonnative dereferences

---

std/algebra/emulated/sw_bls12381/doc_test.go
std/algebra/emulated/sw_bn254/doc_test.go
std/algebra/emulated/sw_bw6761/doc_test.go
std/commitments/kzg/native_doc_test.go
std/commitments/kzg/nonnative_doc_test.go
std/lookup/logderivlookup/doc_test.go
std/math/cmp/doc_isless_test.go
std/math/emulated/doc_example_field_test.go
std/math/emulated/field_hint_test.go
std/multicommit/doc_test.go
std/recursion/groth16/native_doc_test.go
std/recursion/groth16/nonnative_doc_test.go
std/selector/doc_map_test.go
std/selector/doc_mux_test.go
std/selector/doc_partition_test.go

Cleaned up the examples in the documentation. Removed print lines to make the examples more succinct and removed "Output" comments from slow examples to speed up testing.

chore: cleanup documentation examples

---

std/algebra/emulated/sw_emulated/doc_test.go

The `doc_test.go` in `sw_emulated` was not passing. Fixed the curve being used in the circuit, the witness points (use the computed `Q` instead of the base point) and added expected outputs.
Fixes #888
N/A

Fix `sw_emulated` test

---

std/recursion/wrapped_hash.go
std/recursion/wrapped_hash_test.go

This PR adds hash function wrappers which allow to hash elements in the current field and return an output in the target field. If necessary, we cut the excess bits. We add both native and in-circuit implementation so that we can compute recursive proofs and verify in-circuit.
Related #848. I think this PR is sufficient for recursion purporses.
Subtask of #847 and related to PR #880 (cherry picked from).
Not benchmarked.

feat: add short-hash wrappers for recursion

---

std/algebra/emulated/sw_emulated/point.go
std/algebra/emulated/sw_emulated/point_test.go
std/algebra/native/sw_bls12377/g1_test.go
std/algebra/native/sw_bls12377/pairing2.go
std/algebra/native/sw_bls24315/g1_test.go
std/algebra/native/sw_bls24315/pairing2.go
std/commitments/fri/fri.go
std/fiat-shamir/transcript.go
std/fiat-shamir/transcript_test.go
std/gkr/gkr.go
std/recursion/wrapped_hash.go
std/recursion/wrapped_hash_test.go
std/sumcheck/sumcheck.go

Implement gnark-crypto compatible Fiat-Shamir transcript using a short MiMC hash for proof recursion.
All tests seem to be working, but I'm not sure about the option `WithDomainSeparation`. I think it is too agressive on gnark-crypto side to enforce domain separation with the `string:` string when hasher has `WriteString` method. I would make it optional as in gnark. Imo right now the behaviour is not documented and quite difficult to debug.
Related #847 
Not benchmarked

feat: Fiat-Shamir transcript using a short hash

---

std/math/emulated/field_ops.go
std/math/emulated/hints.go

When we count the new overflow for the multiplication result in field emulation, then part of the computation depends on the number of limbs of the multiplication result. Previously, we used `uint(math.Log2(float64(2*nbResLimbs-1)))+1`, but this lead to inconsistent results when `nbResLimbs` was 0. In that case we take log2 of a negative value which is `NaN`. However, on ARM `uint(NaN) = 0` but on x86 `uint(NaN) = math.Max`.
We now use `bits.Len` which is correct for all platforms and avoids doing cast to floating point values.
Additionally, added a check that in case we compute number of limbs for two inputs both having zero inputs. Reviewing code-base, this edge case does not happen, but adding as a protective measure.
This bug appeared when we compoute inverse and division overflows. …

fix: use platform independent method for counting new multiplication overflow from result limb count

---

constraint/bls12-377/system.go
constraint/bls12-381/system.go
constraint/bls24-315/system.go
constraint/bls24-317/system.go
constraint/blueprint.go
constraint/blueprint_logderivlookup.go
constraint/bn254/system.go
constraint/bw6-633/system.go
constraint/bw6-761/system.go
constraint/tinyfield/system.go
internal/generator/backend/template/representations/system.go.tmpl
test/engine.go

See https://github.com/Consensys/gnark/issues/898 . 
Adds `blueprint.Reset()` and `BlueprintLookup` now maintains a cache of resolved entries during solving time.

feat: cache lookup blueprint entries in solving phase

---

std/algebra/emulated/fields_bw6761/e6.go
std/algebra/emulated/fields_bw6761/e6_pairing.go

This PR revisits the addition chains that appear in the final exponentiation of the emulated BW6-761 pairing. Profiling shows that we can widen a bit more the weights of cyclotomic squares and multiplication in the chains generation. 
Current tests apply. 
This PR saves 169518 SCS.

Perf: optimize addition chains in BW6-761 final exponentiation

---

std/algebra/emulated/sw_emulated/point.go
std/algebra/emulated/sw_emulated/point_test.go
std/algebra/native/sw_bls12377/g1_test.go
std/algebra/native/sw_bls12377/pairing2.go
std/algebra/native/sw_bls24315/g1_test.go
std/algebra/native/sw_bls24315/pairing2.go
std/commitments/kzg/verifier.go
std/recursion/plonk/doc.go
std/recursion/plonk/native_doc_test.go
std/recursion/plonk/nonnative_doc_test.go
std/recursion/plonk/opts.go
std/recursion/plonk/verifier.go
std/recursion/plonk/verifier_test.go
std/recursion/wrapped_hash.go
std/recursion/wrapped_hash_test.go

This PR adds in-circuit verifier supporting commitments for both 2-chain and emulated computations.
Fixes #847

feat: add PLONK in-circuit verifier

---

std/algebra/emulated/sw_emulated/point.go

A tiny PR to use GLV in JointScalarMulBase (needed for ECDSA verifier and ECRECOVER precompile). This takes down the ECRECOVER precompile SCS count from **1.2M** to **688k**.
Tests in `std/signature/ecdsa` and `std/evmprecompiles` pass. 
For ECDSA-Secp256k1 in a B254 SNARK:
- SCS:
|                            | Old                           | New                        |
| --------------- | ------------------- | ------------------ |
| ECDSA verifier  |        1,204,561          |         682,603         |
| ECRECOVER     |        1,210,308          |         688,362         |
- R1CS:
|                            | Old                           | New                        |
| --------------- | ------------------- | ------------------ |
| ECDSA verifier  |      310,721               | …

perf(ecdsa): use GLV in JointScalarMulBase

---

frontend/cs/r1cs/api.go
frontend/cs/scs/api.go

Hi there, thanks for your amazing work!
In the current implementation of gnark, `builder.Select` introduces a constraint to enforce that the condition is boolean. However, when the condition is from the result of `builder.IsZero`, this constraint is unnecessary, as `builder.IsZero` always returns a value `m` that is guaranteed to be either 0 or 1.
This PR marks `m` in `builder.IsZero` as boolean, so that we can save 1 constraint when using the result in subsequent operations like `Select`.

perf: mark the result of `builder.IsZero` as boolean to save constraints when used in future

---

go.mod
go.sum
std/compress/lzss/snark.go
std/compress/lzss/snark_test.go

- test: highlight failing test
- build: update compress version

feat: update compress version; failing test

---

std/recursion/plonk/native_doc_test.go
std/recursion/plonk/nonnative_doc_test.go

While studying in-circuit verification with PLONK, I found the existing examples to be of great help. During my research, I discovered some flaws in them and decided to correct these issues for others who might evaluate the same feature in the future.
~Fixes # (issue)~ Currently, there is no dedicated ticket reporting this problem. This PR is primarily a convenience change that does not alter the actual library code. Therefore, I did not think it was necessary to open a ticket. However, please let me know if doing so is required; I would be happy to create one and update this paragraph accordingly.
These examples are not actual Golang tests, but converting them for such use is straightforward. What I did was simply rename `func Example_emulated()` to `func Example_emulated(t *testing.T)` …

Fix std/recursion/plonk native and emulated examples

---

std/algebra/algopts/algopts.go
std/algebra/emulated/sw_emulated/hints.go
std/algebra/emulated/sw_emulated/point.go
std/algebra/emulated/sw_emulated/point_test.go
std/algebra/interfaces.go
std/evmprecompiles/07-bnmul.go

Another tiny PR to use GLV with safe handling of edge cases in EVM `ecmul` precompile.
Tests in `bn_test.go` pass.
ECMUL precompile cost goes from **781,437** to **673,659** SCS.

perf(ecmul): use GLV with safe handling of edge cases in EVM ecmul

---

std/recursion/plonk/verifier_test.go
std/recursion/wrapped_hash.go

Reported by @readygo67 in #1000.
For proof recursion, we are using "short-hash". When computing Fiat-Shamir challenges in-circuit then instead of emulating the whole MiMC hash in non-native, we instead use the native hash of the circuit and map the values to the target field. For this mapping, we have to perform binary decomposition of the inputs and outputs to ensure that the constructed elements fit into the field.
We had a premature optimization for the case where the target field and native field are the same, then we omitted the binary decomposition by using native hash instead. However, this doesn't work well with the rest of the stack (Fiat-Shamir transcript object and recursion implementations), as we do not exclude bits what the rest of the stack assumes are removed.
It would be …

fix: remove shorthash override for same field

---

std/recursion/plonk/doc.go
std/recursion/plonk/verifier.go
std/recursion/plonk/verifier_test.go

Currently we didn't switch on the circuit size and generator when doing multi-proof verification. This PR includes these parts in PLONK verification key in circuit specific VK. Additionally, had to change the exponentiation by the circuit size to use variable instead of a constant.
Related #966 
All current tests work. 
Previously verifying over 10 proofs cost was 291527, now 313833, so approx 7% increase. BUT, for the example circuits the circuits we were aggregating were small and we did fixed exponetiation, so only essentially a few non-native muls. Now we do variable exponentiation for 30-bit exponents. But circuits in practice are actually closer to 30 bits (25-26 bits imo), so the difference shouldn't be that significant.

feat: different PLONK circuit verification

---

std/recursion/groth16/verifier.go

We forgot to update Groth16 verifier circuit to use `NewG2AffineFixed` for `deltaNeg` and `gammaNeg` in `ValueOfVerifyingKeyFixed` for all curves.
Tests in `verifier_test.go` in `std/recursion/groth16` pass.
_(WIP: should benchmark for example bn254-over-bn254 and bn254-over-bw6-761)_

perf: groth16 verifier circuit uses precomputed lines for all curves

---

go.mod
go.sum
std/gkr/api_test.go
std/gkr/gkr.go

Fixes failed assertion while verifying GKR solution(`(gkr.Solution).Verify` function) with other than non-constant hash functions (like mimc or poseidon). Inspired by https://github.com/Consensys/gnark-crypto/blob/master/ecc/bn254/fr/gkr/gkr.go#L688
I added new test case `TestMiMCFullDepthNoDepSolveWithMiMCHash`, which fails without this change with following error:
```
Error:      	Received unexpected error:
constraint #37111 is not satisfied: [assertIsEqual] 10420734889032269308690831442195287995987323506521353207282897974178519295845 == 19485199868485599785212267512534296132678646505698908814492864400056160446973
r1cs.(*builder).AssertIsEqual
/Users/ahmety/gnark/frontend/cs/r1cs/api_assertions.go:38
gkr.(*eqTimesGateEvalSumcheckLazyClaims).VerifyFinalEval …
```

fix: assign baseChallenge correctly while verifying gkr solution

---

std/algebra/emulated/sw_emulated/point.go
std/algebra/emulated/sw_emulated/point_test.go
std/algebra/interfaces.go
std/algebra/native/sw_bls12377/pairing2.go
std/algebra/native/sw_bls12377/pairing2_test.go
std/algebra/native/sw_bls24315/pairing2.go
std/algebra/native/sw_bls24315/pairing2_test.go
std/math/emulated/element_test.go
std/math/emulated/field_ops.go
std/recursion/plonk/verifier.go
std/recursion/plonk/verifier_test.go

This PR changes the mux from `Lookup2` to `selector.Mux` which allows arbitrary switching. The change is backwards compatible (previously we threw an error if had more than 4 keys).
Fixes #966 
PLONK recursion over 10 proofs increase from 313833 to 314402.

feat: use n-bit mux for switching PLONK verification keys

---

std/compress/lzss/snark.go
std/compress/lzss/snark_test.go

Currently, when the output buffer `d` is not long enough to contain the decompressed stream, `Decompress` returns `dLength = 0` which is seen as a valid output. This PR changes that to -1 which in any cryptographic prime-order field is so large it cannot be confused with a valid output length.
[`TestOutBufTooShort`](https://github.com/Consensys/gnark/blob/fix/compressor/truncated-input/std/compress/lzss/snark_test.go#L106)
No benchmark. Performance impact expected to be negligible.

fix: Decompressor to return -1 when output doesn't fit

---

std/math/emulated/field_assert.go
std/math/emulated/regression_test.go

Thanks @hussein-aitlahcen for reporting and helping to debug. It was a difficult one 👍 
To show that two field elements are equal, we instead show that the difference of the field elements is a multiple of emulated modulus. However, for computing the difference we used non-reducing version of subtraction to avoid infinite cycles. With the new mulmod implementation the reducing versions do not call AssertIsEqual anymore so the infinite cycles are averted. Previously, for some edge cases the difference may overflow scalar field and solving may fail (see [here](https://github.com/Consensys/gnark/issues/1021#issuecomment-1916763099))
Fixes #1021 
Existing tests succeed.
Not benchmarked.

fix: use subtraction with reduce in AssertIsEqual

---

std/commitments/kzg/verifier.go

In #949 we optimized in KZG folding to use curve basepoint to evaluate foldedEval, but KZG SRS G1 generator may be different. This PR reverts the change.
Tests work downstream in Linea prover.

fix: use G1 generator from SRS

---

std/commitments/kzg/verifier.go

#1035 was incomplete. This completes it.

fix: another occurence of G1 in SRS

---

std/algebra/emulated/sw_emulated/point.go
std/algebra/emulated/sw_emulated/point_test.go

`jointScalarMulGeneric` is used to compute `[u]P+[v]Q` when the GLV endomorphism is not a available. It was implementing it naively as most of the curves of interest to us have GLV. But users might want for example to verify ECDSA with NIST curves e.g. P-256, P-384 — in which case this PR might come in handy.
Added test `TestJointScalarMul4` and `TestJointScalarMulEdgeCases4` (edge casess involving 0-scalars and (0,0)-points) for P-256 curve (no GLV).
old: 1418482 scs
new: 1186170 scs

perf(sw_emulated): optimize jointScalarMulGeneric

---

std/algebra/emulated/sw_bls12381/pairing.go
std/algebra/emulated/sw_bw6761/doc_test.go
std/algebra/emulated/sw_bw6761/g1.go
std/algebra/emulated/sw_bw6761/g2.go
std/algebra/emulated/sw_bw6761/pairing.go
std/algebra/emulated/sw_bw6761/pairing_test.go
std/algebra/native/sw_bls12377/g1.go
std/algebra/native/sw_bls12377/g2.go
std/algebra/native/sw_bls12377/pairing2.go
std/algebra/native/sw_bls12377/pairing_test.go

This PR adds G1 and G2 subgroup memberships for BW6-761. It's up to the user to call these circuits for example before a pairing call.
Added new tests for subgroup membership tests.
- For BLS12-377:
|                     | G1 curve membership | G2 curve membership | G1 subgroup membership | G2 subgroup membership |
| ----------- | ----------- | ----------- | -------------- | ------------- |
| SCS             | 11 | 32  | 971     |  2,267  |
So a total of 3,280 (without separate equality checks of each sub-circuit) if we want to test all membership for e.g. before a pairing circuit.
- For BW6-761:
|                     | G1 curve membership | G2 curve membership | G1 subgroup membership | G2 subgroup membership |
| ----------- | ----------- | ----------- | -------------- | ------------- | …

feat: subgroup G1/G2 membership BW6-761 and BLS12-377

---

constraint/bls12-377/solver.go
constraint/bls12-381/solver.go
constraint/bls24-315/solver.go
constraint/bls24-317/solver.go
constraint/bn254/solver.go
constraint/bw6-633/solver.go
constraint/bw6-761/solver.go
constraint/solver/options.go
constraint/tinyfield/solver.go
internal/generator/backend/template/representations/solver.go.tmpl
internal/regression_tests/issue1048/issue1048_test.go

This PR allows restricting the number of threads in solver. This is mainly useful for debugging the solver as the solving order is deterministic.
Fixes #1048

feat: add option for enforcing number of goroutines for the solver

---

frontend/cs/scs/api.go
frontend/cs/scs/api_test.go
frontend/cs/scs/builder.go

In `addConstraintExist` and `mulConstraintExist` we re-use cached constraints to avoid introducing new ones and compute a division for the output wire. But when some of the coefficients are 0 we panic because of a `div by 0`. This PR avoids this by checking if the coefficient is 0. 
The test `TestVarScalarMulG2EdgeCases` in https://github.com/Consensys/gnark/blob/7cc8816179d5a257c770da506cbb8789b19be20b/std/algebra/native/sw_bls12377/g2_test.go#L288 fails for PLONK without this PR.
N/A

fix: scs add/mul when recorded constraint is 0

---

std/math/emulated/field_hint.go
std/math/emulated/field_test.go

Related to #1061.
This PR adds an optional methods for calling hints with native inputs or outputs. For example, in #1061 we use it to return the sign bits for the non-native inputs. By being more precise with the native inputs and outputs, we can save constraints due not having to range check the created elements.
Not benchmarked.

feat: add hint calling with either native inputs or outputs

---

std/math/emulated/field_test.go

Fixes tests not appearing in PR CI. Include hints in solver and add a dummy constraint to have larger than of size 1.
- Tests succeeding now.

fix: emulated hint tests

---

std/math/emulated/element_test.go
std/math/emulated/field_mul.go
std/math/emulated/field_ops.go

Non-reducing multiplication can be useful in contexts where we craft the non-native operations in a order where we know that we're going to use addition chains after. Doing this allows us to call the modular reduction later, saving constraints due to not having to reduce twice (before and after addition chains). For example, the approach can be used for computing inner products, where we first compute `a_i * b_i`, then compute `c = \sum_i a_i * b_i` and finally only reduce `c` once.
Depends on #1064 being merged.
New methods, no impact on existing performance.

feat: add MulNoReduce and Sum methods in field emulation

---

frontend/cs/r1cs/api_assertions.go
frontend/cs/r1cs/builder.go
frontend/cs/r1cs/r1cs_test.go
frontend/cs/scs/api_test.go
frontend/cs/scs/builder.go

The issue has been reported by @wuestholz. When we perform `x = api.Sub(A, A)`, then we do not take the fast path that `x` is a constant zero neither for scs or r1cs builder.
Not benchmarked

perf/fix: assume variable as zero constant when subtracting from itself

---

frontend/cs/scs/builder.go

This PR adds an option to retrieve the IDs of the wire which were range checked through `frontend.Checker` interface.
cc @AlexandreBelling 
Tested in Wizard.

feat: add range check selector retrieval

---

std/algebra/defaults.go
std/algebra/emulated/sw_emulated/point.go

Adds secp256k1 for the `std/algebra` package method `GetCurve` based on base and scalar field. It is not pairing friendly curve, so haven't implemented the corresponding method for `GetPairing`.
This helper is useful for curve agnostic curve operation implementations.
Additionally, as the secp256k1 curve in gnark-crypto currently is handwritten instead of code-generated and we do not marshal infinity points separately, then added a fast path for point marshalling which corresponds to gnark-crypto. The issue being that we do not have space for the infinity bits as the scalar field is 256 bits.
Only helper methods.
Not benchmarked

feat: add secp256k1 curve default initializer

---

std/math/polynomial/polynomial.go
std/math/polynomial/polynomial_oldeval_test.go
std/math/polynomial/polynomial_test.go
std/recursion/sumcheck/claimable_gate.go
std/recursion/sumcheck/claimable_multilinear.go

This PR optimizes evaluation of multilinear polynomials.
Previously, we folded the multilinear polynomial one variable at a time, but this is sub-optimal approach when using non-native arithmetic as we have to perform many modular multiplications.
Now, instead, we split the variables `x1, ..., xn` into two similar size partitions `x1, .., x_{n/2}` and `x_{n/2+1}, ..., xn`. We then compute recursively all possible combinations `prod({x1, (1-x1)}, ..., {x_{n/2}, 1-x_{n/2}})` and `prod({x_{n/2+1}, (1-x_{n/2+1})}, ..., {x_n, 1-x_n})` first and then compute the corresponding evaluated coefficients `(1-x1)*...*(1-xn) f0` ... `x1*...*xn f_{2^n}` one by one with the combinations using non-reducing multiplication and addition chains.
With doing the addition chains and non-reducing multiplications, …

perf: non-native multilinear polynomial evaluation

---

backend/groth16/bn254/solidity.go
std/math/polynomial/polynomial_test.go

Addresses some causes for `Stack too deep` or `memoryguard was present` compiler errors by using assembly to copy calldata to an array. Tracked as part of issue #1094 .

feat: groth16 solidity use calldatacopy for commitments

---

std/signature/ecdsa/doc.go
std/signature/ecdsa/ecdsa.go
std/signature/eddsa/doc.go
std/signature/eddsa/eddsa.go

update documentation for ecdsa and eddsa, especially the constraints count in comments (see https://github.com/Consensys/gnark/discussions/1112).
N/A
N/A

docs: update documentation for ecdsa and eddsa

---

std/algebra/emulated/sw_emulated/point.go
std/algebra/native/sw_bls12377/g1.go
std/algebra/native/sw_bls24315/g1.go

Remove todos. These are future optimizations for cases that are never used but only present as a fallback.
N/A
N/A

refactor: remove todos

---

std/recursion/plonk/verifier_test.go

Example test for PLONK proof aggregation which adds one circuit for mapping the per-inner circuit public input to a single outer-circuit public input

test: add PLONK test for public input mapping

---

backend/groth16/bls12-377/marshal.go
backend/groth16/bls12-377/marshal_test.go
backend/groth16/bls12-381/marshal.go
backend/groth16/bls12-381/marshal_test.go
backend/groth16/bls24-315/marshal.go
backend/groth16/bls24-315/marshal_test.go
backend/groth16/bls24-317/marshal.go
backend/groth16/bls24-317/marshal_test.go
backend/groth16/bn254/marshal.go
backend/groth16/bn254/marshal_test.go
backend/groth16/bw6-633/marshal.go
backend/groth16/bw6-633/marshal_test.go
backend/groth16/bw6-761/marshal.go
backend/groth16/bw6-761/marshal_test.go
backend/groth16/groth16.go
go.mod
go.sum
internal/generator/backend/template/zkpschemes/groth16/groth16.marshal.go.tmpl
internal/generator/backend/template/zkpschemes/groth16/tests/groth16.marshal.go.tmpl
io/io.go
io/roundtrip.go

Sister PR to https://github.com/Consensys/gnark-crypto/pull/501 .
Essentially, addresses the issue of slow deserialization for (large) proving keys. `ReadFrom` and `UnsafeReadFrom` can take many seconds (if not minutes) due to subgroup checks, point decompression and "safe" point reconstruction (involve at least converting `[]byte` canonical field elements into Montgomery repr).
This PR introduces `pk.WriteDump` and `pk.ReadDump` for scenarios where want to minimize loading time, don't need portability (uses `unsafe`; `pk.ReadDump` must read a stream generated by `pk.WriteDump` on a similar architecture: 32/64 bit little/big endian (most popular platforms these days are 64bits little endian)), and don't need to perform any sanity checks.
A quick bench for a medium sized …

perf,feat: groth16.ProvingKey implements BinaryDumper using gnark-crypto unsafe

---

frontend/cs/scs/builder.go

When extracting the constraint indices for range checking, we didn't take into account the added constraints rows in the traces which account for the public inputs. We now shift the constraint indices by the number of public variables.
In zkevm repo.
Not benchmarked. But added an optimization to break the loop early when all results have been found.

fix: shift constraint indices by nb of public vars

---

std/math/emulated/composition.go

This PR collects various fixes to non-native arithmetic with variable modulus:
- in case the provided variable modulus in non-native arithmetic is zero, then return more descriptive panic trace

fix: non-native arithmetic with variable modulus various fixes

---

std/commitments/kzg/verifier_test.go

check KZG batch verify returned error in test circuit
Already covered with existing tests

test: check KZG batch verify returned error in test circuit

---

constraint/string_utils.go
examples/rollup/circuit.go
examples/rollup/operator.go

make function comments match function names
Docs

chore: make function comments match function names

---

std/math/uints/uint8.go
std/math/uints/uint8_test.go

As stated in the TODO, `uints8.ValueOf` is not constrained. This commit constrains the output of ValueOf. 
I am jumping in on the deep end with circuit development, so would appreciate as much feedback as possible. Especially would appreciate guidance on testing constraints for intermediate values, the overflow was the only technique I could think of that works in a unit test.
Added a unit test that if added to the current master branch will fail. The third test case should return an error as the input exceeds the output size.

fix(uints): constrain valueOf

---

std/evmprecompiles/05-expmod.go
std/math/emulated/emparams/emparams.go

The PR allows the caller of ExpMod to specify which field parameter to use for the circuit generation as the current implemenentation fixes a size of 4096.
The PR also adds the 256 bit variant of Mod1e512
This is required for the integration in the prover. 
The changes did not break existing calling code.
No test have been added specifically for the changes
No benchmark have been done.

Make ExpMod work with parametric fields parameters

---

std/math/bitslice/opts.go
std/math/bitslice/partition.go
std/math/bitslice/partition_test.go

Fixes #1153.
Also handle separately case when `nbDigits >= Fr width` as we need to check that we do not overflow and use unique decomposition. There isn't a better way beyond doing bit-by-by comparison against the modulus, so this case is deferred to `math/bits` package.
Added some package documentation.
Shouldn't affect current usage of the implementation as we call everywhere with `nbDigits` small.

fix(math/bitslice): fix partition upper part range check width

---

backend/groth16/bls12-377/verify.go
backend/groth16/bls12-381/verify.go
backend/groth16/bls24-315/verify.go
backend/groth16/bls24-317/verify.go
backend/groth16/bn254/solidity.go
backend/groth16/bn254/verify.go
backend/groth16/bw6-633/verify.go
backend/groth16/bw6-761/verify.go
backend/groth16/groth16.go
backend/plonk/plonk.go
backend/solidity/solidity.go
backend/solidity/verifyingkey.go
internal/generator/backend/template/imports.go.tmpl
internal/generator/backend/template/zkpschemes/groth16/groth16.verify.go.tmpl
test/assert_checkcircuit.go
test/assert_options.go
test/assert_solidity.go

PR https://github.com/Consensys/gnark/pull/1138 changed the implementation of `VerifyingKey.ExportSolidity` and due to that the CI tests for Solidity started to fail.
This PR resolves the interface definition
(ran full test suite locally to ensure Solidity verifier is run)

fix: groth16 solidity templates

---

std/rangecheck/rangecheck_commit.go

Fixes https://github.com/Consensys/gnark/issues/1192
```
GOOS=linux GOARCH=arm go build
GOOS=linux GOARCH=386 go build
```
- Before this PR and after this PR, `go build` always success. 
- This PR would fix gomobile Android binding https://github.com/Consensys/gnark/issues/1192#issuecomment-2221872640
Btw, some unit tests would also raise int overflow under 32-bit Arch
```bash
➜  gnark git:(master) GOOS=linux GOARCH=arm /usr/local/go/bin/go test
internal/backend/circuits/div.go:17:24: cannot use 2387287246 (untyped int constant) as int value in argument to api.DivUnchecked (overflows)
internal/backend/circuits/inv.go:17:19: cannot use 2387287246 (untyped int constant) as int value in argument to api.Inverse (overflows)
internal/backend/circuits/mul.go:30:11: cannot use 92149106544 …
```

Fix: Build on 32-bit arch would raise int overflow

---

frontend/cs/r1cs/builder.go
frontend/internal/expr/linear_expression.go
frontend/internal/expr/term.go
std/math/emulated/field.go

Fixes #1146.
Instead of a fast hash non-cryptographic hash use cryptographically secure hash. Previously it was possible for a malicious circuit designer to define a circuit in a way which would omit either boolean marking or non-native element range checking by creating collisions between variables. This PR avoids this by using a strong hash function instead.
NB! It uses as hash outputs only 16 bytes instead of full 32 bytes for saving some memory.
Existing tests pass
For example, I compiled the BW6-671 PLONK verifier in BN254 as one of the biggest circuits to get estimates in possible performance bottlenecks. Results:
```
SCS:
* time 37.39810504s
* mem 32498MB
R1CS:
* time 46.508562287s
* mem 65606MB
SCS:
* time 37.215583182s
* mem 32430MB
R1CS:
* time 47.082183625s
* mem 66455MB
```
So …

feat: use blake2 for variable hashcode

---

std/hash/mimc/doc.go
std/hash/mimc/mimc.go
std/recursion/wrapped_hash.go

Certain use cases of MiMC may lead to length extension attacks. Document these cases to help the users avoid them.
This will follow up with a PR on gnark-crypto to give the same considerations.
Fixes #1141

docs: describe potential length extension attack when using MiMC in-circuit

---

std/algebra/emulated/fields_bn254/e2.go
std/algebra/emulated/sw_bn254/g2.go
std/algebra/emulated/sw_bn254/pairing.go
std/algebra/emulated/sw_bn254/pairing_test.go

This method allows to check for non-membership. In case we need to assert membership it is still more efficient to use `AssertIsOnG2` as then we don't have to call `IsZero` for non-native elements which is more expensive that `AssertIsEqual`.
@yelhousni - can you recommend better naming for the methods? I think this could generalize to other curves, but right now needed for Linea, so omitted the implementation.

feat: add IsOnG2 for BN254

---

frontend/cs/scs/builder.go

Previously, we only checked if the variable to be range checked externally was at L xor R locations in the gate. In this PR we remove the restrictions that we can use a gate only a single variable range check. Additionally, we also output now if the variable is in the O location in the gate.
In downstream usage

feat: capture O variable in gate for external range checker

---

std/algebra/native/sw_bls24315/g1.go
std/algebra/native/sw_bls24315/g2.go
std/algebra/native/sw_bls24315/hints.go
std/algebra/native/sw_bls24315/pairing2.go

We use GLV for scalar multiplication in 2-chains (BLS12-377 and BLS24-315). For the decomposition of scalar to be valid we have to check that `s1 + λ s2 = s` where `s` is the initial scalar and `s1`, `s2` are the decomposed values (width length 127 bits).
For BLS12-377 we can perform this check using native arithmetic as we constrain s1, s2, λ to all be 127 bits and we never overflow the outer curve scalar field (width 377 bits).
However, for BLS24-315 we have `λ` with `256` bits and in this case the check `s1 + λ s2 = s` may overflow the native field. We compensate for it by giving additional output from the hint which cancels out the overflowed value, but this gives the malicious prover some advantage for finding invalid inputs.
Safer approach would be to perform the arithmetic using …

fix: use emulated arithmetic for GLV decomp

---

std/multicommit/nativecommit.go

Fixes #1203 
Current test suite

fix: use consecutive powers instead of squaring

---

std/algebra/emulated/fields_bn254/e12_pairing.go
std/algebra/emulated/sw_bn254/hints.go
std/algebra/emulated/sw_bn254/pairing.go

Fixes #1213 
Same tests.
no change.

fix: avoid malicious hint in BN254 final exp check

---

std/algebra/emulated/fields_bn254/e12.go
std/algebra/emulated/fields_bn254/e6.go
std/algebra/emulated/sw_bn254/pairing.go
std/algebra/emulated/sw_bn254/pairing_test.go
std/evmprecompiles/08-bnpairing.go

In some cases we are interested to obtain the value if the final exponentiation resulted in 1 or not instead of asserting. Refactor and add such method.
With this, also renamed `FinalExpCheck` to `AssertFinalExpCheck` to better distinguish different methods.

feat: add BN254 final exponentiation check with output

---

std/algebra/emulated/sw_bn254/hints.go
std/algebra/emulated/sw_bn254/pairing.go

PR #1214 removed usage of possible malicious hint value from the circuit. However, we still output the variables in circuit which are then enforced to be range checked. In gnark it leads to unnecessary constraints and in zkevm it creates problem with the external range checker as we're looking for constraints where this variables are used.
Current CI. Only cosmetic change.

fix: remove unconstrained and unused variables

---

std/evmprecompiles/08-bnpairing.go

In zkevm we use three separate circuits for efficiency (documented in zkevm repository).
Depends on https://github.com/Consensys/gnark/pull/1209.
In downstream usage

refactor: separate the fixed circuits for ECPairing used in zkevm

---

std/math/emulated/custommod.go
std/math/emulated/hints.go

This PR fixes some of the methods used in testing the variable modulus case in field emulation:
* correctly set the next overflow
* assert that the subtraction padding is big enough
* check that the next overflow wouldn't the native field
We currently only panic when the next overflow would overflow the native field, in contrast to the behaviour with fixed emulated modulus where we then would mod-reduce the value automatically. As `modSub` is not directly exposed and used in equality assertion (which is then only used in tests), then it should be sufficient for now.
Fixes #1152
Existing tests pass.

fix: variable modulus subtraction padding

---

std/algebra/algopts/algopts.go
std/algebra/emulated/sw_emulated/point.go
std/algebra/interfaces.go
std/algebra/native/sw_bls12377/pairing2.go
std/algebra/native/sw_bls24315/pairing2.go
std/math/emulated/element.go
std/math/emulated/element_test.go
std/math/emulated/field_assert.go
std/math/emulated/field_binary.go
std/math/emulated/field_ops.go
std/math/emulated/field_reduce.go

Fixes https://github.com/Consensys/gnark/issues/1147, but more thoroughly. Added separate method which performs modular reduction and asserts that the result is in range. Updated the documentation accordingly.
Additionally, added an option to algebra methods to obtain the canonical bit representation if necessary (when comparing bitwise some values).
The current implementation are not modified - if the prover would provide `x+p` from the hint, then the recursion implementations fail to solve as we have incorrect FS challenges.
We now have reduction in the 2-chain PLONK verifier as previously when performing binary decomposition of BLS12 points we used canonical decomposition, but now by default we don't.

fix: strict ModReduce in emulated fields

---

std/math/emulated/element_test.go

Fixes big CI error. In Reduce test when emulating Goldilocks we only had a single constraint, but PLONK setup phase assumes circuit of size at least two.
The circuit size check is already defined in several issues: https://github.com/Consensys/gnark/issues/864, https://github.com/Consensys/gnark/issues/967. I also have locally open branch to add more helpful errors in case the circuit size is 0 or 1.
CI

fix: edge case with PLONK backend when 1 constraint

---

frontend/cs/r1cs/api_assertions.go
frontend/cs/scs/api_assertions.go
internal/regression_tests/issue1227/issue_1227_test.go

Fixes an edge case introduced by #1228 ; thanks to @wuestholz for reporting.

fix: minimum 1 bit for constant binary decomposition

---

frontend/cs/scs/api_assertions.go

branch with unchecked cast could panic at compile time, thanks to @wuestholz  for reporting.

fix: branch with unchecked cast could panic at compile time

---

frontend/cs/scs/api.go
internal/regression_tests/issue1246/issue1246_test.go

fix: fixes #1246 ensure cond is boolean in `api.Select`

---

constraint/bls12-377/gkr.go
constraint/bls12-381/gkr.go
constraint/bls24-315/gkr.go
constraint/bls24-317/gkr.go
constraint/bn254/gkr.go
constraint/bw6-633/gkr.go
constraint/bw6-761/gkr.go
internal/generator/backend/template/representations/gkr.go.tmpl
std/gkr/api_test.go
std/gkr/compile.go
std/gkr/hints.go
test/engine.go

Currently, GKR cannot run under the test engine. This PR changes that by implementing hints that delegate to the appropriate curve-specific ones used in the solver.

feat test engine friendly GKR

---

profile/internal/graph/dotgraph.go
profile/profile_worker.go

refactor: use strings.ReplaceAll

---

backend/groth16/bn254/solidity.go
backend/groth16/bn254/verify.go
backend/plonk/bn254/verify.go
backend/solidity/solidity.go
backend/solidity/solidity_test.go
internal/generator/backend/template/zkpschemes/groth16/groth16.verify.go.tmpl
internal/generator/backend/template/zkpschemes/plonk/plonk.verify.go.tmpl
test/assert_checkcircuit.go
test/assert_solidity.go

To allow different compatibility, it is beneficial to support different hash-to-field functions to hash the commitments to field in Solidity contract. This PR extends the `ExportSolidity` method to take in options which allow changing the functions. Later, we could possibly use the extendability to also change the HTF function for PLONK Solidity verifier, but keeping unchanged for now.
Also added `TargetSolidity` options for the prover and verifier which chooses all the parameters optimally for Solidity verifier. For PLONK prover it is currently no-op, but this allows more simply to change the hash functions we use within (with corresponding little gas savings).
Ref #1094 
In package `backend/solidity`:
And the subtests 
Not benchmarked, only changes Solidity verifier

feat: allow configurable hash-to-field function for Groth16 Solidity verifier

---

CHANGELOG.md
README.md
doc.go
docs/CITATION.bib

Release v0.11.0 preparation work.

release: v0.11.0

---

go.mod
go.sum
std/recursion/wrapped_hash.go

update gnark-crypto to latest which removes support of BLS12-378 and BW6-756 curves
`wrapped_hash_test.go` in std/recursion passes.
N/A

chore: up gnark-crypto

---

test/unsafekzg/kzgsrs.go
test/unsafekzg/options.go

This PR fixes (i.e. always the same value) the randomness used in unsafe KZG SRS production. This results in getting the same SRS for a given domain every time, and even the same verifying key for different domain sizes over the same curve.
The intended application of this are tests involving batch verification of commitments - for example when verifying multiple PlonK proofs.

feat constant 'randomness' - domain-size-independent vk

---

frontend/api.go
frontend/cs/scs/api.go
frontend/cs/scs/builder.go

- Minor API doc edits
- Remove scs/api.go api comments; godoc will use the one defined in the interface by default which is better.

docs: update api doc following audit suggestions

---

profile/internal/graph/graph.go

The intention here should be to initialize a slice with a capacity of  `len(prof.Location)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW

fix: fix slice init length

---

std/evmprecompiles/01-ecrecover.go
std/evmprecompiles/01-ecrecover_test.go

We followed the implementation of libsecp256k1 where v was allowed to be {0,1,2,3}. However, EVM specification has restricted allowed v to be only 0 or 1 for both transactions and precompiles.
From Linea arithmetization POV shouldn't have been an issue as the arithmetization already constrains v to be 0 or 1 and doesn't pass inputs to gnark circuit when v is something else:
Resolves LA audit issue F.
Existing tests pass.
Added:
Not benchmarked, but should reduce a few constraints due to one less select and boolean check.

fix: allow only v=0 or v=1

---

backend/groth16/bls12-377/marshal_test.go
backend/groth16/bls12-381/marshal_test.go
backend/groth16/bls24-315/marshal_test.go
backend/groth16/bls24-317/marshal_test.go
backend/groth16/bn254/marshal_test.go
backend/groth16/bn254/solidity.go
backend/groth16/bw6-633/marshal_test.go
backend/groth16/bw6-761/marshal_test.go
go.mod
go.sum
internal/generator/backend/template/zkpschemes/groth16/tests/groth16.marshal.go.tmpl
internal/tinyfield/element_test.go
internal/tinyfield/vector.go
std/commitments/pedersen/assignment.go
std/commitments/pedersen/verifier.go

To update changes incorporated in https://github.com/Consensys/gnark-crypto/pull/548.
TODO! update gnark-crypto dependency in this PR to master after gnark-crypto PR is merged so that we have good reference point (not to a tangling commit in a PR).

chore: Pedersen verification key reference field

---

std/evmprecompiles/05-expmod.go
std/evmprecompiles/05-expmod_test.go

Even though EVM yellow paper defines 0^0=1, then this holds only if modulus is not 0 or 1. In either such case any exponentiation is 0.
Fixes LA audit Issue G
Not benchmarked

fix: expmod precompile if modulus is 1

---

examples/inputpacking/doc.go
examples/inputpacking/inputpacking_test.go

Add an example on how to use a hash of the public inputs to optimize for calldata and proof recursion complexity.

docs: add input packing example

---

frontend/schema/schema.go
frontend/schema/walk.go

As far as I can tell, there's only two places (outside of tests) that still are using `fmt.Printf`/`fmt.Println` to print warnings to stdout, in the `frontend/schema` directory. This small PR replaces them with warning logs using the `logger` module.
If the severity of the message should be different from a warning, let me know so I can change it quickly.
I've tested this locally against a test case that triggers this message (specifically https://github.com/argumentcomputer/sphinx doing a Plonk BN254 proof verification, via an FFI wrapper at https://github.com/argumentcomputer/lurk-hs), and with this patch the messages are now logged at the proper level, as follows:
Before:
```
Testing fixture: "/home/w/dev/w/lurk-hs/assets/epoch_change.json"
ignoring uninitialized slice: Vars …
```

chore: Replace fmt.Printf calls with warning logs

---

std/recursion/groth16/verifier.go

When using a fixed verification key in Groth16 recursive prover, we do not initialize the public committed variables. This leads to a recursion error when using a fixed key.
See https://github.com/Consensys/gnark/issues/1306#issuecomment-2477870738
The test case in the discussion

fix: initialize public committed

---

logger/logger.go

In the comment for the `Set` function, there is a typo. The original comment reads:
```go
// Set allow a gnark user to overhide the global logger
```
**Fixed version:**
```go
// Set allows a gnark user to override the global logger
```
**Explanation of the fix:**
- The verb **"allow"** should be **"allows"** since the subject of the sentence is the function name `Set`, which is singular. 
- The word **"overhide"** is incorrect. The correct term here is **"override"**, which is commonly used to refer to replacing or modifying the behavior of an existing function or setting.
This fix ensures that the comment is grammatically correct and clearly communicates the intended meaning.

Fix typo Update logger.go

---

frontend/api.go

**Description:**  
This pull request fixes a typo in the documentation of the `MulAcc` method in the `API` interface.  
In the documentation, the example for the `MulAcc` method currently reads:  
```  
acopy = MulAcc(acopy, b, c)  
```  
This is inconsistent with other examples in the documentation, which explicitly reference the API object using the `api.` prefix. The omission of `api.` in this example could confuse readers, particularly those new to the interface, as they might not realize that `MulAcc` is intended to be invoked as a method of the `API` object.  
The corrected line is:  
```  
acopy = api.MulAcc(acopy, b, c)  
```  
- **Clarity:** Ensures consistency in the documentation, aligning this example with other examples.  
- **Accuracy:** Prevents potential confusion for …

Fix typo Update api.go

---

frontend/builder.go
frontend/variable.go

**Changes:**
1. **In `frontend/builder.go`:**
- Fixed the grammatical error in the comment for the `MarkBoolean` method. The original comment was:
> "MarkBoolean sets (but do not constraint!) v to be boolean"
- Corrected to:
> "MarkBoolean sets (but does not constrain!) v to be boolean"
- **Explanation**: The word "constraint" was used incorrectly. The verb should be "constrain" as it follows the auxiliary verb "does" which requires the infinitive form.
2. **In `frontend/variable.go`:**
- Fixed the plural form of "builder" in the comment for the `IsCanonical` function. The original comment was:
> "by one of the constraint system builder."
- Corrected to:
> "by one of the constraint system builders."
- **Explanation**: The sentence refers to multiple potential builders, so the correct form …

Fix typos in comments for clarity and grammatical correctness

---

profile/profile.go

**Description:**
This pull request addresses the following spelling errors in the code:
1. **In the comment at the beginning of the file:**
- Corrected **"profiile"** to **"profile"**.
2. **In the description of the Profile structure:**
- Corrected **"profiile"** to **"profile"**.
**Importance:**
These spelling mistakes, although minor, could cause confusion for developers reading the code, especially those who may not be familiar with the structure or who rely on accurate documentation. Consistent and accurate spelling is crucial for maintaining clarity and professionalism in code comments and documentation.

Typo Update profile.go

---

std/math/emulated/doc.go
std/math/emulated/element_test.go
std/math/emulated/field.go
std/math/emulated/field_mul.go
std/math/emulated/hints.go

This PR adds direct multivariate polynomial evaluation using non-native arithmetic. It can be used to perform direct extension computation, used in pairing computation (BW6, BN254, BLS12-377).
The idea is very similar to the multiplication approach, but when we do the evaluation check then we can work with arbitrary multivariate polynomials. This is really beneficial as the most of the cost is in range checking the result and the quotient, so when we can amortize multiple operations.
Another PR using it in BW6 evaluation is incoming, but it saves more than 50% of constraints in the Miller loop computation.
NB! One thing which I haven't figure out is how to allow negative coefficients. For example for BW6 we need to multiply by the non residue -4 for which we currently use a non-native …

feat: direct multivariate polynomial evaluation in non-native

---

CHANGELOG.md
SECURITY.md
go.mod
go.sum
std/hash/poseidon2/poseidon2.go
std/hash/poseidon2/poseidon2_test.go
std/math/emulated/doc.go
std/math/emulated/element_test.go
std/math/emulated/field.go
std/math/emulated/field_mul.go
std/math/emulated/hints.go

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `finel` to `final`
Corrected `occurence` to `ccurrence`
Corrected `swith` to `switch`
Corrected `adjustement` to `adjustment`
Corrected `initialisation` to `initialization`
Corrected `compatiblity` to `compatibility`
Corrected `jacobain` to `jacobian`
`Releases ,` (extra space before the comma) — it should be `releases,`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

std/algebra/emulated/sw_bls12381/pairing.go
std/algebra/emulated/sw_bls12381/pairing_test.go
std/algebra/emulated/sw_bn254/pairing.go
std/algebra/emulated/sw_bn254/pairing_test.go

Replaces a select on Ext6 with one on just the first field element.
We check if the Ext6 is zero so we don't need to change all the elements and just the first one (from `0` to `1`) if all of them are `0`.
This saves a couple bunch of constraints. Added a benchmark to test number of constraints for final exponentiation.
```diff
➜  gnark git:(master) ✗ go test -benchmem -run=^$ -bench ^BenchmarkFinalExponentiation$ github.com/consensys/gnark/std/algebra/emulated/sw_bn254 -v
goos: darwin
goarch: arm64
pkg: github.com/consensys/gnark/std/algebra/emulated/sw_bn254
cpu: Apple M3 Pro
BenchmarkFinalExponentiation
BenchmarkFinalExponentiation/compile_scs
BenchmarkFinalExponentiation/compile_scs-12                    1        1936695834 ns/op        3169885256 B/op 20046059 allocs/op
- …
```

final exponentiation: select optimisation

---

frontend/api.go
std/commitments/fri/fri.go
std/multicommit/doc_test.go

fix some struct and interface names in comment

chore: fix some struct and interface names in comment

---

backend/groth16/bn254/solidity.go

Fixes  bn254 solidity template

fix bn254 solidity template

---

std/algebra/emulated/fields_bls12381/e12_pairing.go
std/algebra/emulated/fields_bn254/e12_pairing.go
std/algebra/emulated/sw_bn254/pairing.go
std/algebra/native/fields_bls12377/e12_pairing.go

Minor optimisation on residue witness scaling cofactor mul.
Changed it to E6 (from E12) for fewer constraints and logic gates.
<table role="table" style="letter-spacing: .1em">
<tbody><tr>
<th rowspan="2"></th>
<th colspan="2">BN254</th>
<th colspan="2">BLS381</th>
</tr>
<tr>
<th>R1CS</th>
<th>SCS</th>
<th>R1CS</th>
<th>SCS</th>
</tr>
<tr style="text-align:right;">
<td>Before</td>
<td><code class="notranslate">1167090</code></td>
<td><code class="notranslate">4586889</code></td>
<td><code class="notranslate">990001</code></td>
<td><code class="notranslate">3879548</code></td>
</tr>
<tr style="text-align:right;">
<td>After</td>
<td><code class="notranslate">1166782</code></td>
<td><code class="notranslate">4586709</code></td>
<td><code class="notranslate">989785</code></td>
<td><code …

Pairing check optimisation

---

std/math/emulated/field_mul.go

This PR fixes edge cases when computing the quotient length. We compute the product length in bits and then to get the quotient length, we subtract the modulus length. But as we work over uints then if the product length is less than the modulus (for example when inputs are short, on one limb), then we get underflow which due to rolling over leads to allocating huge slices. This crashes the prover.
Also fixed a potential edge case in carry computation.
Tested with #1339

fix: NNA quotient length computation edge cases

---

README.md
backend/groth16/bn254/icicle/device.go
backend/groth16/bn254/icicle/doc.go
backend/groth16/bn254/icicle/icicle.go
backend/groth16/bn254/icicle/marshal_test.go
backend/groth16/bn254/icicle/noicicle.go
backend/groth16/bn254/icicle/provingkey.go
backend/groth16/groth16.go
go.mod
go.sum

Icicle depends on cgo and external dependencies which are not available for Mac/Windows and on machines when CUDA is not available. Also guard other methods behind build tag when it is not explicitly provided.

fix: avoid linking icicle dependent files when tag not provided

---

std/algebra/emulated/sw_bls12381/g1.go
std/algebra/emulated/sw_bls12381/g2.go
std/algebra/emulated/sw_bls12381/pairing.go
std/algebra/emulated/sw_bn254/g2.go
std/algebra/emulated/sw_bw6761/g1.go
std/algebra/emulated/sw_emulated/point.go

Forgot to push this in #1349. 
G1 and G2 subgroup membership using Eval for curve and twist arithmetics. 
`TestGroupMembershipSolve` passes.
This saves **101,565 scs** for `GroupMembershipCircuit`.

perf: G1/2 membership using Eval

---

std/algebra/emulated/sw_bn254/pairing.go

Super minor optimisation to replace a div with a mul, for exponentiation by `λ' = q^3 - q^2 + q`. We already have the inv so we can just exp the inverse by `q^2` and mul (instead of exp and div).

optim: avoid div in millerLoopAndFinalExpResult

---

internal/stats/latest_stats.csv
std/algebra/emulated/sw_bn254/g2.go
std/algebra/emulated/sw_bn254/g2_test.go
std/algebra/emulated/sw_bn254/pairing.go
std/algebra/emulated/sw_bn254/precomputations.go
std/evmprecompiles/08-bnpairing.go

Including G2 subgroup membership in the pairing computations saves a lot of constraints. For Linea zkEVM, gnark circuit has only to check G2 membership as the arithemtization does the check for G1.
In `computeLines` the accumulated point is `[6x₀+2]Q` (`x₀` being the curve seed). We can tweak* the subgroup membership to check `[6x₀+2]Q + ψ(Q) + ψ³(Q) == ψ²(Q)` instead of `ψ³([2x₀]Q) - ψ²([x₀]Q) - ψ([x₀]Q) - [x₀]Q == Q`. This saves the multiplication by `6x₀+2` and enforces G2 membership check systematically in pairing calls, simplifying probably the Wizard glue. 
\* since `x₀ ≠ 4 mod 13 and x₀ ≠ 92  mod 97` for BN254, `V=(6x₀+ 2,1,−1,1)` is also a valid short vector.
_TL;DR: G2 subgroup membership becomes ~2 point additions instead of ~81 point additions._
All current tests pass.
On one …

perf(bn254): include G2 membership check in ML

---

std/algebra/emulated/sw_bn254/g2.go

PR #1387 introduced implicit G2 membership check during lines computation. This allows to avoid separate G2 membership test.
However, when the G2 points is given as a constant (i.e. embedded in the circuit description), for example in recursive proof verification, then we don't explicitly check the G2 membership for the constant point. This PR adds this check.
Existing tests pass

fix: add G2 membership check for constant points

---

constraint/solver/hint_registry.go
examples/rollup/circuit.go
examples/rollup/operator.go
frontend/schema/tags.go
std/algebra/emulated/sw_bn254/pairing.go
std/polynomial/polynomial.go

This PR stashes multiple PRs addressing typos and code simplifications. Ready to be merged.

fix: stashed typo fixes for v0.12

---

std/math/emulated/element_test.go
std/math/emulated/field_assert.go
std/math/emulated/field_mul.go
std/math/emulated/field_ops.go

When the compiler can deduce that non-native element is constant zero, then we represent it on zero limbs. However in `IsZero` method we initialized the accumulator from first limb without range checking. This PR adds fast path for constant zero.
Fixes #1412

fix: non-native zero IsZero edge case

---

std/hash/hash.go
std/hash/sha2/sha2.go
std/hash/sha2/sha2_test.go
std/hash/sha3/hashes.go
std/hash/sha3/sha3.go
std/hash/sha3/sha3_test.go

Use minLen to reduce the times of selects and optimize the FixedLengthSum of hash.
In practice, the length of a piece of data to be hashed is variable, but its minimum value is rarely 0. In this case, if minLen is passed to FixedLengthSum, a lot of constraints can be saved. For example, in the project we are currently working on, one of the data lengths to be hashed ranges from 1680 to 1710. Using the new FixedLengthSum can reduce about 200,000 constraints, as shown in the results of Test_SHA3FixedLengthSum_WithMinLen_VS_Zero:
```
=== RUN   Test_SHA3FixedLengthSum_WithMinLen_VS_Zero
maxLen=1710, minLen=1680, hash=Keccak-512, nbConstraints: 6696856 vs 6555681(withMinLen)
maxLen=1710, minLen=1680, hash=SHA3-256, nbConstraints: 4040628 vs 3796970(withMinLen)
maxLen=1710, minLen=1680, …
```

optimize FixedLengthSum of hash with minLen

---

backend/groth16/bls12-377/mpcsetup/phase1.go
backend/groth16/bls12-381/mpcsetup/phase1.go
backend/groth16/bls24-315/mpcsetup/phase1.go
backend/groth16/bls24-317/mpcsetup/phase1.go
backend/groth16/bn254/mpcsetup/phase1.go
backend/groth16/bw6-633/mpcsetup/phase1.go
backend/groth16/bw6-761/mpcsetup/phase1.go
internal/generator/backend/template/zkpschemes/groth16/mpcsetup/phase1.go.tmpl

Fixes a bug where `SameRatioMany` was run on `p` (previous contribution) rather than `next` (new contribution) which means the ratios on the very last contribution are not checked.

fix: Ratio Verification on Groth16 MPC - Phase 1

---

README.md
backend/backend.go
backend/groth16/bn254/icicle/device.go
backend/groth16/bn254/icicle/icicle.go
backend/groth16/bn254/icicle/provingkey.go
go.mod
go.sum

Link against the OSS version of ICICLE. Also update some changed APIs
Tested an example ECDSA circuit locally. It is not committed as we don't have GPU accelerated CI anyway and it requires a setup.

feat: use OSS ICICLE for GPU acceleration (version v3.2.2)

---

go.mod
go.sum
std/algebra/emulated/sw_emulated/point_test.go

Resolves #1483 by updating gnark-crypto which fixes the convergence.
- Added edge case test for small negative scalar

fix: fake glv neg scalars

---

std/math/emulated/element_test.go
std/math/emulated/field_ops.go

For non-native arithmetic Lookup2 and Mux we used Lookup2 and Mux on individual limbs. We normalized the inputs so that we would always have the same number of limbs, but when we did the final Lookup2/Mux, we only range over the number of limbs the first input had.

fix: range over all limbs in normalized form for lookup

---

CHANGELOG.md
README.md
doc.go
docs/CITATION.bib

Release has already been done. This only updates the main branch after the tagged version. We cannot update the tag as it would break package cache (particularly go mod!).

release: v0.13.0

---

frontend/cs/r1cs/api_assertions.go

Update the Zcash protocol specification link in api_assertions.go from the GitHub repository path to the official Zcash documentation site. This ensures access to the most up-to-date version of the specification.

fix: update Zcash protocol specification link

---

std/math/emulated/field_hint_test.go
test/unsafekzg/kzgsrs.go

Fixes failing test on master. Our PLONK backend doesn't support proving single constraint circuit proving, but we already failed before when the test suite tried to generate SRS for it and had out of bounds access.

fix: single constraint unsafe KZG SRS in tests

---

std/algebra/emulated/sw_bls12381/g2.go
std/evmprecompiles/11-blsg1add.go
std/evmprecompiles/12-blsg1msm.go
std/evmprecompiles/13-blsg2add.go
std/evmprecompiles/14-blsg2msm.go
std/evmprecompiles/16-blsmaptog1.go
std/evmprecompiles/17-blsmaptog2.go
std/evmprecompiles/bls_test.go

Corresponding downstream usage in https://github.com/Consensys/linea-monorepo/pull/915. This PR modifies the interfaces for the EVM precompile gadgets for better compatibility with the glue logic.

refactor: BLS EVM precompile integration

---

constraint/solver/hint_registry.go

Fix bug where RegisterHint would stop registering subsequent hint functions if one function was already registered. 
Changed `return` to `continue` to ensure all functions in the slice are processed.
This bug could cause missing hint function registrations leading to solver errors.

fix: prevent early return in RegisterHint causing missing registrations

---

std/commitments/kzg/verifier.go
std/commitments/kzg/verifier_test.go

This PR implements complete formulas for KZG proof verification to allow checking proofs for zero polynomials and constructed polynomials.
Maybe there is a more efficient way than using complete formulas for MSM which adds quite a lot of overhead. But it seems that we don't use this method directly, for PLONK recursive verifier we manually prepare the inputs and use batch verification where we already have an option to use complete formulas.
Maybe here we could also add an option for using complete formulas? Although for me it seems that it is a valid case to commit to a zero polynomial and I'd rather have a default behaviour which allows it, rather than not.
For PLONK previously 2701912, now 2772838. Diff 70926
For Groth16 previously 713893, now 734527. Diff 20634
It doesn't seem to …

fix: KZG proof verification for edge cases

---

std/recursion/groth16/verifier.go

This PR fixes several typo-level mismatches in error messages and one vector type in the Groth16 recursion helpers:
- ValueOfProof: bw6-761 branch
- expected bls24315.Proof → expected bw6761.Proof
- ValueOfVerifyingKey (non-Fixed version):
- bls12-377 branch: expected bn254.VerifyingKey → expected bls12377.VerifyingKey
- bls24-315 branch: expected bls12381.VerifyingKey → expected bls24315.VerifyingKey
- ValueOfWitness: bw6-761 branch
- expected fr_bls24315.Vector → expected fr_bw6761.Vector
N/A
N/A

feat: correct curve names in error messages and vector type

---

std/math/polynomial/polynomial.go

- Add early return in EvalUnivariate when len(P)==0 to return 0 (zero polynomial evaluation) instead of panicking on P[0].
- Add early error in EvalMultilinearMany when len(M)==0 to avoid panicking on M[0] and clearly signal invalid input.
- These changes align behavior with existing conventions (e.g., evaluators returning zero for empty input) and harden the API against out-of-range panics, improving robustness without altering normal-path performance.

Handle empty inputs in EvalUnivariate and EvalMultilinearMany

---

std/recursion/plonk/verifier.go

Correct the expected type strings in error messages within ValueOfProof, ValueOfBaseVerifyingKey, and ValueOfCircuitVerifyingKey for bw6-761 and bn254. Previously, these branches incorrectly referenced bls12377 types. Fixing these messages ensures accurate diagnostics when type mismatches occur, aligning with the actual backend types used (plonkbackend_bw6761.*, plonkbackend_bn254.*) and matching the conventions used for other curves.

plonk(recursion): fix incorrect error messages for bw6-761 and bn254 branches

---

constraint/babybear/r1cs_test.go
constraint/bls12-377/r1cs_test.go
constraint/bls12-381/r1cs_test.go
constraint/bls24-315/r1cs_test.go
constraint/bls24-317/r1cs_test.go
constraint/bn254/r1cs_test.go
constraint/bw6-633/r1cs_test.go
constraint/bw6-761/r1cs_test.go
constraint/koalabear/r1cs_test.go
constraint/tinyfield/r1cs_test.go
internal/generator/backend/template/representations/tests/r1cs.go.tmpl

Generated R1CS serialization tests were using `t.Fatal(nil)` instead of `t.Fatal(err)` 
when handling ReadFrom errors, causing tests to fail without proper error context.
ixed the generator template `internal/generator/backend/template/representations/tests/r1cs.go.tmpl` 
to use `t.Fatal(err)` and regenerated all affected test files.
- Template: `internal/generator/backend/template/representations/tests/r1cs.go.tmpl`
- Generated tests: All `constraint/*/r1cs_test.go` files

fix: propagate ReadFrom errors in generated r1cs tests

---

std/algebra/emulated/sw_bls12381/g1.go
std/algebra/emulated/sw_bls12381/g1_test.go
std/algebra/emulated/sw_bls12381/map_to_g1.go

Tiny PR to use affine point tripling in G1 mul by seed for BLS12-381 curve.
MapToG1 and ClearCofactor tests pass.
Saves 450 scs.

perf(bls12-381/map-to-g1): use triple in mul by seed
